/* BuildWise AI — admin property editing + street-first display */
(function(){document.head.insertAdjacentHTML('beforeend','<style>#di-nav-sideNav,#di-nav-mobileNav,#di-nav-bottomNav{display:none!important}</style>');
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const n=x=>x===''||x==null?null:Number(x);
 const money=x=>x==null||x===''||Number.isNaN(Number(x))?'—':Number(x).toLocaleString('fa-IR'); const yn=v=>v===true?'بله':v===false?'خیر':(v??'—');
 window.propertyCard=function(x){const title=x.street||x.property_name||x.property_code||'ملک بدون عنوان';return '<article class="property-card" data-search="'+esc([x.street,x.property_name,x.property_code,x.neighborhood,x.property_type].join(' '))+'" data-type="'+esc(x.property_type||'')+'"><div class="property-top"><span class="code">'+esc(x.property_code||'بدون کد')+'</span><span class="badge">'+esc(x.status||'فعال')+'</span></div><h3>'+esc(title)+'</h3><p>'+esc(x.property_type||'')+' · منطقه '+esc(x.region||'—')+' · '+esc(x.neighborhood||'—')+'</p><div class="property-meta"><span>'+money(x.built_area)+' متر</span><span>'+(x.bedrooms??'—')+' خواب</span><span>'+money(x.price_per_meter)+' / متر</span></div><strong class="price">'+money(x.total_price)+'</strong><div class="modal-actions">'+(window.canWrite?.()!==false?'<button class="btn" onclick="editProperty('+x.id+')">ویرایش</button>':'')+'</div></article>'};
 window.properties=async function(){const r=await db.from('properties').select('id,property_code,property_name,property_type,region,neighborhood,street,land_area,built_area,bedrooms,total_price,price_per_meter,mobile,status,description,created_at').order('created_at',{ascending:false}).limit(100);main.innerHTML=page('املاک','بانک فایل مستقل از خواهان‌ها و معاملات',canWrite()?btn('+ افزودن ملک','propertyForm()',true):'')+'<div class="toolbar"><input id="propertyQ" placeholder="جستجوی نام، خیابان، محله یا کد" oninput="filterProperties()"><select id="propertyTypeFilter" onchange="filterProperties()"><option value="">همه انواع</option><option>آپارتمان</option><option>زمین</option><option>ویلایی</option><option>تجاری</option><option>اداری</option></select></div><div id="property-list" class="data-grid">'+(r.error?errbox(r.error):(r.data||[]).map(propertyCard).join('')||empty('ملکی ثبت نشده است','از دکمه افزودن ملک شروع کنید.'))+'</div>'};
 window.filterProperties=function(){const q=(window.propertyQ?.value||'').toLowerCase(),t=window.propertyTypeFilter?.value||'';document.querySelectorAll('#property-list > *').forEach(x=>x.style.display=((x.dataset.search||'').toLowerCase().includes(q)&&(x.dataset.type===t||!t))?'':'none')};
 window.editProperty=async function(id){if(!canWrite())return toast('دسترسی ویرایش ندارید','error');const r=await db.from('properties').select('*').eq('id',id).single();if(r.error)return toast(r.error.message,'error');const x=r.data;modal('<h2>ویرایش فایل</h2><div class="form-grid"><label>نام فایل<input id="ep_name" value="'+esc(x.property_name||'')+'"></label><label>خیابان<input id="ep_street" value="'+esc(x.street||'')+'"></label><label>نوع ملک<input id="ep_type" value="'+esc(x.property_type||'')+'"></label><label>منطقه<input id="ep_region" type="number" value="'+esc(x.region??'')+'"></label><label>محله<input id="ep_neighborhood" value="'+esc(x.neighborhood||'')+'"></label><label>زمین<input id="ep_land" type="number" value="'+esc(x.land_area??'')+'"></label><label>زیربنا<input id="ep_area" type="number" value="'+esc(x.built_area??'')+'"></label><label>خواب<input id="ep_bed" type="number" value="'+esc(x.bedrooms??'')+'"></label><label>قیمت کل<input id="ep_price" type="number" value="'+esc(x.total_price??'')+'"></label><label>قیمت متری<input id="ep_ppm" type="number" value="'+esc(x.price_per_meter??'')+'"></label><label>موبایل<input id="ep_mobile" inputmode="tel" value="'+esc(x.mobile||'')+'"></label><label>وضعیت<select id="ep_status"><option value="active">فعال</option><option value="inactive">غیرفعال</option><option value="draft">پیش‌نویس</option><option value="closed">بسته</option></select></label></div><label>توضیحات<textarea id="ep_desc" rows="4">'+esc(x.description||'')+'</textarea></label><div class="modal-actions"><button class="btn" onclick="closeModal()">انصراف</button><button class="btn primary" onclick="saveEditedProperty('+id+')">ذخیره تغییرات</button></div>');document.getElementById('ep_status').value=x.status||'active'};
 window.saveEditedProperty=async function(id){if(!canWrite())return;const payload={property_name:ep_name.value.trim(),street:ep_street.value.trim(),property_type:ep_type.value.trim(),region:n(ep_region.value),neighborhood:ep_neighborhood.value.trim(),land_area:n(ep_land.value),built_area:n(ep_area.value),bedrooms:n(ep_bed.value),total_price:n(ep_price.value),price_per_meter:n(ep_ppm.value),mobile:ep_mobile.value.trim(),status:ep_status.value,description:ep_desc.value.trim()};const r=await db.from('properties').update(payload).eq('id',id);if(r.error)return toast(r.error.message,'error');closeModal();await properties();toast('فایل با موفقیت ویرایش شد','success')};

window.viewProperty=async function(id){
 const r=await db.from('properties').select('*').eq('id',id).single();
 if(r.error)return toast(r.error.message,'error');
 const x=r.data, fields=[
 ['کد فایل',x.property_code],['نوع درخواست',x.request_type],['نوع ملک',x.property_type],['مالکیت',x.ownership_type],['کاربری',x.usage_type],
 ['منطقه',x.region],['محله',x.neighborhood],['خیابان',x.street],['کوچه',x.alley],['خیابان فرعی',x.side_street],['پلاک',x.plaque],
 ['عرض',x.width],['مساحت زمین',x.land_area],['زیربنا',x.built_area],['طبقه',x.floor],['کل طبقات',x.total_floors],['تعداد خواب',x.bedrooms],
 ['سن بنا',x.building_age],['سال ثبت',x.year_registered],['تعداد واحد',x.unit_count],['پارکینگ',x.parking_count],['انباری',x.storage_count],['آسانسور',yn(x.elevator)],
 ['تراکم',x.density],['طبقات مجاز',x.allowed_floors],['سطح اشغال',x.occupancy_percent],['عقب‌نشینی',x.setback],['وضعیت سند',x.title_status],
 ['وضعیت پروانه',x.permit_status],['وضعیت تکمیل',x.completion_status],['قیمت کل',money(x.total_price)],['قیمت متری',money(x.price_per_meter)],
 ['ودیعه کامل',money(x.full_deposit)],['ودیعه',money(x.deposit_amount)],['اجاره',money(x.rent_amount)],['قیمت پیشنهادی مالک',money(x.owner_asking_price)],
 ['قیمت قابل مذاکره',money(x.negotiable_price)],['تهاتر',yn(x.barter_possible)],['شرایط پرداخت',x.payment_terms],['موبایل',x.mobile],
 ['نام مالک',x.owner_name],['وضعیت فعالیت',x.activity_status],['نوع آگهی',x.listing_type],['توضیحات',x.description],['یادداشت مالک',x.owner_notes],['یادداشت داخلی',x.internal_notes]
 ];
 modal('<h2>'+esc(x.street||x.property_name||'جزئیات کامل فایل')+'</h2><div class="full-property-grid">'+fields.map(([k,v])=>'<div><small>'+esc(k)+'</small><strong>'+esc(v==null||v===''?'—':v)+'</strong></div>').join('')+'</div><div class="modal-actions">'+(canWrite()?'<button class="btn primary" onclick="editProperty('+id+')">ویرایش</button>':'')+'<button class="btn" onclick="closeModal()">بستن</button></div>');
};
window.propertyCard=function(x){const title=x.street||x.property_name||x.property_code||'ملک بدون عنوان';return '<article class="property-card" data-search="'+esc([x.street,x.property_name,x.property_code,x.neighborhood,x.property_type,x.request_type,x.year_registered,x.building_age,x.listing_type].join(' '))+'" data-type="'+esc(x.property_type||'')+'" data-request="'+esc(x.request_type||x.listing_type||'')+'" data-price="'+esc(x.total_price??'')+'" data-bed="'+esc(x.bedrooms??'')+'" data-region="'+esc(x.region??'')+'"><div class="property-top"><span class="code">'+esc(x.property_code||'بدون کد')+'</span><span class="badge">'+esc(stateLabel(x.status))+'</span></div><h3>'+esc(title)+'</h3><p>'+esc(x.property_type||'')+' · منطقه '+esc(x.region||'—')+' · '+esc(x.neighborhood||'—')+'</p><div class="property-meta"><span>'+money(x.built_area)+' متر</span><span>'+(x.bedrooms??'—')+' خواب</span><span>'+money(x.price_per_meter)+' / متر</span><span>ساخت '+esc(x.year_registered||x.building_age||'—')+'</span></div><strong class="price">'+money(x.total_price)+'</strong><div class="modal-actions"><button class="btn" onclick="viewProperty('+x.id+')">نمایش کامل</button>'+(canWrite()?'<button class="btn" onclick="editProperty('+x.id+')">ویرایش</button>':'')+'</div></article>'};
window.properties=async function(){const r=await db.from('properties').select('*').order('created_at',{ascending:false}).limit(100);main.innerHTML=page('املاک','نمایش کامل بانک فایل و فیلتر عملیاتی',canWrite()?btn('+ افزودن ملک','propertyForm()',true):'')+'<div class="toolbar property-filters"><input id="propertyQ" placeholder="جستجوی نام، خیابان، محله، کد یا سال ساخت" oninput="filterProperties()"><select id="propertyRequestFilter" onchange="filterProperties()"><option value="">خرید/فروش/رهن/اجاره — همه</option><option value="فروش">فروش</option><option value="رهن">رهن</option><option value="اجاره">اجاره</option><option value="رهن و اجاره">رهن و اجاره</option></select><select id="propertyTypeFilter" onchange="filterProperties()"><option value="">نوع ملک — همه</option><option>کلنگی</option><option>زمین</option><option>آپارتمان</option><option>تجاری</option><option>اداری</option><option>ویلایی</option></select><input id="propertyMinPrice" type="number" placeholder="حداقل قیمت" oninput="filterProperties()"><input id="propertyMaxPrice" type="number" placeholder="حداکثر قیمت" oninput="filterProperties()"><input id="propertyMinBed" type="number" min="0" placeholder="حداقل خواب" oninput="filterProperties()"><input id="propertyRegion" type="number" placeholder="منطقه" oninput="filterProperties()"></div><div id="property-list" class="data-grid">'+(r.error?errbox(r.error):(r.data||[]).map(propertyCard).join('')||empty('ملکی ثبت نشده است','از دکمه افزودن ملک شروع کنید.'))+'</div>'};
window.filterProperties=function(){const q=(window.propertyQ?.value||'').toLowerCase().trim(),t=window.propertyTypeFilter?.value||'',rq=window.propertyRequestFilter?.value||'',min=Number(window.propertyMinPrice?.value||0),max=Number(window.propertyMaxPrice?.value||0),bed=Number(window.propertyMinBed?.value||0),reg=window.propertyRegion?.value||'';document.querySelectorAll('#property-list > *').forEach(x=>{const p=Number(x.dataset.price||0),b=Number(x.dataset.bed||0),okQ=!q||(x.dataset.search||'').toLowerCase().includes(q),okT=!t||(x.dataset.type||'').includes(t),okR=!rq||(x.dataset.request||'').includes(rq),okMin=!min||p>=min,okMax=!max||p<=max,okBed=!bed||b>=bed,okReg=!reg||x.dataset.region===reg;x.style.display=okQ&&okT&&okR&&okMin&&okMax&&okBed&&okReg?'':'none'})};
window.runAdvancedSearch=async function(){searchResults.innerHTML=busy('در حال جستجو...');let q=db.from('properties').select('*').limit(200);if(s_region.value)q=q.eq('region',n(s_region.value));if(s_neighborhood.value)q=q.ilike('neighborhood','%'+s_neighborhood.value.trim()+'%');if(s_type.value)q=q.ilike('property_type','%'+s_type.value.trim()+'%');if(s_min.value)q=q.gte('total_price',n(s_min.value));if(s_max.value)q=q.lte('total_price',n(s_max.value));if(s_bed.value)q=q.gte('bedrooms',n(s_bed.value));if(document.getElementById('s_year')?.value)q=q.eq('year_registered',document.getElementById('s_year').value.trim());if(document.getElementById('s_request')?.value)q=q.ilike('request_type','%'+document.getElementById('s_request').value.trim()+'%');const r=await q;searchResults.innerHTML=r.error?errbox(r.error):(r.data||[]).map(propertyCard).join('')||empty('نتیجه‌ای پیدا نشد','فیلترها را کمی بازتر کنید.')};
const s=document.createElement('style');
s.textContent=".full-property-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.full-property-grid>div{background:#f7f9f9;border:1px solid #e4e8ea;border-radius:9px;padding:10px;display:flex;flex-direction:column;gap:4px}.full-property-grid small{color:#7a858c;font-size:10px}.full-property-grid strong{font-size:12px}.property-filters{flex-wrap:wrap}.property-filters>*{min-width:130px}.property-filters input:first-child{min-width:260px}@media(max-width:760px){.full-property-grid{grid-template-columns:1fr}.property-filters>*{width:100%}}";
document.head.appendChild(s);
window.search=async function(){
  main.innerHTML=page('جستجوی هوشمند','فیلتر ترکیبی فایل‌ها بر اساس قیمت، خواب، لوکیشن، سال ساخت و نوع معامله')+
    '<section class="card search-panel"><div class="form-grid">'+
    '<label>منطقه<input id="s_region" type="number"></label>'+
    '<label>محله / خیابان<input id="s_neighborhood"></label>'+
    '<label>نوع ملک<select id="s_type"><option value="">همه</option><option>کلنگی</option><option>زمین</option><option>آپارتمان</option><option>تجاری</option><option>اداری</option><option>ویلایی</option></select></label>'+
    '<label>نوع معامله<select id="s_request"><option value="">همه</option><option>فروش</option><option>رهن</option><option>اجاره</option><option>رهن و اجاره</option></select></label>'+
    '<label>حداقل قیمت<input id="s_min" type="number"></label>'+
    '<label>حداکثر قیمت<input id="s_max" type="number"></label>'+
    '<label>حداقل خواب<input id="s_bed" type="number" min="0"></label>'+
    '<label>سال ساخت<input id="s_year" placeholder="مثلاً 1402"></label>'+
    '</div><button class="btn primary" onclick="runSearch()">جستجو</button></section><div id="searchResults"></div>';
};
window.runSearch=window.runAdvancedSearch;
})();
