/* BuildWise AI — admin property editing + street-first display */
(function(){document.head.insertAdjacentHTML('beforeend','<style>#di-nav-sideNav,#di-nav-mobileNav,#di-nav-bottomNav{display:none!important}</style>');
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const n=x=>x===''||x==null?null:Number(x);
 const money=x=>x==null||x===''||Number.isNaN(Number(x))?'—':Number(x).toLocaleString('fa-IR');
 window.propertyCard=function(x){const title=x.street||x.property_name||x.property_code||'ملک بدون عنوان';return '<article class="property-card" data-search="'+esc([x.street,x.property_name,x.property_code,x.neighborhood,x.property_type].join(' '))+'" data-type="'+esc(x.property_type||'')+'"><div class="property-top"><span class="code">'+esc(x.property_code||'بدون کد')+'</span><span class="badge">'+esc(x.status||'فعال')+'</span></div><h3>'+esc(title)+'</h3><p>'+esc(x.property_type||'')+' · منطقه '+esc(x.region||'—')+' · '+esc(x.neighborhood||'—')+'</p><div class="property-meta"><span>'+money(x.built_area)+' متر</span><span>'+(x.bedrooms??'—')+' خواب</span><span>'+money(x.price_per_meter)+' / متر</span></div><strong class="price">'+money(x.total_price)+'</strong><div class="modal-actions">'+(window.canWrite?.()!==false?'<button class="btn" onclick="editProperty('+x.id+')">ویرایش</button>':'')+'</div></article>'};
 window.properties=async function(){const r=await db.from('properties').select('id,property_code,property_name,property_type,region,neighborhood,street,land_area,built_area,bedrooms,total_price,price_per_meter,mobile,status,description,created_at').order('created_at',{ascending:false}).limit(100);main.innerHTML=page('املاک','بانک فایل مستقل از خواهان‌ها و معاملات',canWrite()?btn('+ افزودن ملک','propertyForm()',true):'')+'<div class="toolbar"><input id="propertyQ" placeholder="جستجوی نام، خیابان، محله یا کد" oninput="filterProperties()"><select id="propertyTypeFilter" onchange="filterProperties()"><option value="">همه انواع</option><option>آپارتمان</option><option>زمین</option><option>ویلایی</option><option>تجاری</option><option>اداری</option></select></div><div id="property-list" class="data-grid">'+(r.error?errbox(r.error):(r.data||[]).map(propertyCard).join('')||empty('ملکی ثبت نشده است','از دکمه افزودن ملک شروع کنید.'))+'</div>'};
 window.filterProperties=function(){const q=(window.propertyQ?.value||'').toLowerCase(),t=window.propertyTypeFilter?.value||'';document.querySelectorAll('#property-list > *').forEach(x=>x.style.display=((x.dataset.search||'').toLowerCase().includes(q)&&(x.dataset.type===t||!t))?'':'none')};
 window.editProperty=async function(id){if(!canWrite())return toast('دسترسی ویرایش ندارید','error');const r=await db.from('properties').select('*').eq('id',id).single();if(r.error)return toast(r.error.message,'error');const x=r.data;modal('<h2>ویرایش فایل</h2><div class="form-grid"><label>نام فایل<input id="ep_name" value="'+esc(x.property_name||'')+'"></label><label>خیابان<input id="ep_street" value="'+esc(x.street||'')+'"></label><label>نوع ملک<input id="ep_type" value="'+esc(x.property_type||'')+'"></label><label>منطقه<input id="ep_region" type="number" value="'+esc(x.region??'')+'"></label><label>محله<input id="ep_neighborhood" value="'+esc(x.neighborhood||'')+'"></label><label>زمین<input id="ep_land" type="number" value="'+esc(x.land_area??'')+'"></label><label>زیربنا<input id="ep_area" type="number" value="'+esc(x.built_area??'')+'"></label><label>خواب<input id="ep_bed" type="number" value="'+esc(x.bedrooms??'')+'"></label><label>قیمت کل<input id="ep_price" type="number" value="'+esc(x.total_price??'')+'"></label><label>قیمت متری<input id="ep_ppm" type="number" value="'+esc(x.price_per_meter??'')+'"></label><label>موبایل<input id="ep_mobile" inputmode="tel" value="'+esc(x.mobile||'')+'"></label><label>وضعیت<select id="ep_status"><option value="active">فعال</option><option value="inactive">غیرفعال</option><option value="draft">پیش‌نویس</option><option value="closed">بسته</option></select></label></div><label>توضیحات<textarea id="ep_desc" rows="4">'+esc(x.description||'')+'</textarea></label><div class="modal-actions"><button class="btn" onclick="closeModal()">انصراف</button><button class="btn primary" onclick="saveEditedProperty('+id+')">ذخیره تغییرات</button></div>');document.getElementById('ep_status').value=x.status||'active'};
 window.saveEditedProperty=async function(id){if(!canWrite())return;const payload={property_name:ep_name.value.trim(),street:ep_street.value.trim(),property_type:ep_type.value.trim(),region:n(ep_region.value),neighborhood:ep_neighborhood.value.trim(),land_area:n(ep_land.value),built_area:n(ep_area.value),bedrooms:n(ep_bed.value),total_price:n(ep_price.value),price_per_meter:n(ep_ppm.value),mobile:ep_mobile.value.trim(),status:ep_status.value,description:ep_desc.value.trim()};const r=await db.from('properties').update(payload).eq('id',id);if(r.error)return toast(r.error.message,'error');closeModal();await properties();toast('فایل با موفقیت ویرایش شد','success')};
})();