/* BuildWise AI Data Import Agent: Excel/CSV + Google Sheets/Drive, 1000-row batches */
(function(){
var U='https://beuestoewletjsgmigmf.supabase.co',K='sb_publishable_dE92Qm9EtMv4sdNRXF7SRg_7ox1xYax',dbi=supabase.createClient(U,K),B=1000,rows=[],target='properties',source='excel';
function E(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function N(x){return String(x==null?'':x).trim().toLowerCase().replace(/[\s\-\/]+/g,'_').replace(/[()]/g,'')}
function num(x){if(x===''||x==null)return null;var s=String(x).replace(/[۰-۹]/g,function(c){return '۰۱۲۳۴۵۶۷۸۹'.indexOf(c)}).replace(/[٠-٩]/g,function(c){return '٠١٢٣٤٥٦٧٨٩'.indexOf(c)}).replace(/[,٬]/g,'').replace(/تومان|ریال/gi,'');var n=Number(s);return isFinite(n)?n:null}
function pick(o,a){for(var i=0;i<a.length;i++){var v=o[N(a[i])];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return ''}
function loadX(){return new Promise(function(ok,no){if(window.XLSX)return ok();var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function open(){if(typeof window.modal!=='function'){alert('BuildWise AI is not ready');return}window.modal('<h2>ورود داده به BuildWise AI</h2><p>Excel/CSV و Google Sheets؛ هر بار حداکثر ۱۰۰۰ رکورد.</p><label>مقصد<select id="di-target"><option value="properties">املاک</option><option value="leads">خواهان‌ها</option><option value="market">داده بازار</option></select></label><label>منبع<select id="di-source"><option value="excel">Excel / CSV</option><option value="sheet">Google Sheets عمومی</option><option value="bridge">Google Drive Bridge</option></select></label><div id="di-sourcebox"></div><div id="di-preview"></div><button id="di-run" class="btn pri" disabled>شروع ورود</button> <button class="btn" onclick="closeModal()">انصراف</button>');document.getElementById('di-target').onchange=sourceBox;document.getElementById('di-source').onchange=sourceBox;sourceBox();document.getElementById('di-run').onclick=run}
function sourceBox(){target=document.getElementById('di-target').value;source=document.getElementById('di-source').value;rows=[];var b=document.getElementById('di-sourcebox');if(source==='excel'){b.innerHTML='<label>فایل<input id="di-file" type="file" accept=".xlsx,.xls,.csv"></label>';document.getElementById('di-file').onchange=readFile}else if(source==='sheet'){b.innerHTML='<label>لینک Google Sheet<input id="di-url" placeholder="https://docs.google.com/spreadsheets/d/..."></label><button id="di-read" class="btn">خواندن</button>';document.getElementById('di-read').onclick=readRemote}else{b.innerHTML='<label>Web App URL پل Google Drive<input id="di-bridge" placeholder="https://script.google.com/macros/s/.../exec"></label><label>Spreadsheet ID<input id="di-id" value="1A24ypEXoOT-10j1V83Qzpn-PcGTwNxmfMB2YkuijeMo"></label><label>GID اختیاری<input id="di-gid" placeholder="0"></label><button id="di-read" class="btn">خواندن Drive</button>';document.getElementById('di-read').onclick=readRemote}}
async function readFile(){try{await loadX();var f=document.getElementById('di-file').files[0];if(!f)return;var wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:''});preview()}catch(e){alert(e.message)}}
function sid(u){var m=String(u).match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);return m?m[1]:''}
function gid(u){var m=String(u).match(/[?&#]gid=(\d+)/);return m?m[1]:'0'}
function csv(t){var ls=t.split(/\r?\n/).filter(Boolean);if(!ls.length)return[];function p(s){var a=[],c='',q=false;for(var i=0;i<s.length;i++){var ch=s[i];if(ch==='"'){q=!q;continue}if(ch===','&&!q){a.push(c);c=''}else c+=ch}a.push(c);return a}var h=p(ls[0]),out=[];for(var j=1;j<ls.length;j++){var a=p(ls[j]),o={};h.forEach(function(k,i){o[k]=a[i]||''});out.push(o)}return out}
async function readRemote(){try{var u;if(source==='sheet'){var id=sid(document.getElementById('di-url').value);if(!id)throw Error('لینک Google Sheet معتبر نیست');u='https://docs.google.com/spreadsheets/d/'+id+'/export?format=csv&gid='+gid(document.getElementById('di-url').value)}else{u=document.getElementById('di-bridge').value.replace(/\/$/,'')+'?action=sheet&sheet_id='+encodeURIComponent(document.getElementById('di-id').value)+(document.getElementById('di-gid').value?'&gid='+encodeURIComponent(document.getElementById('di-gid').value):'')}var r=await fetch(u);if(!r.ok)throw Error('Google پاسخ نداد');var t=await r.text();try{var j=JSON.parse(t);if(j.error)throw Error(j.error);rows=j.rows||[]}catch(_){rows=csv(t)}preview()}catch(e){alert(e.message)}}
function mapProperty(o){return {property_code:String(pick(o,['property_code','code','کد','کد_ملک'])||('IMP-'+Date.now()+'-'+Math.random().toString(36).slice(2,8))),source:source,property_type:pick(o,['property_type','type','نوع_ملک','نوع']),ownership_type:pick(o,['ownership_type','نوع_مالکیت']),usage_type:pick(o,['usage_type','کاربری']),region:num(pick(o,['region','zone','منطقه'])),neighborhood:pick(o,['neighborhood','area_name','محله']),street:pick(o,['street','خیابان']),alley:pick(o,['alley','کوچه']),side_street:pick(o,['side_street','فرعی']),plaque:pick(o,['plaque','پلاک']),frontage:num(pick(o,['frontage','width','عرض_بر'])),passage_width:num(pick(o,['passage_width','عرض_کوچه'])),land_area:num(pick(o,['land_area','land','زمین','مساحت_زمین'])),built_area:num(pick(o,['built_area','area','metrage','متراژ','زیربنا'])),floor:num(pick(o,['floor','طبقه'])),total_floors:num(pick(o,['total_floors','floors','طبقات'])),bedrooms:num(pick(o,['bedrooms','rooms','خواب'])),building_age:num(pick(o,['building_age','age','سن_بنا'])),unit_count:num(pick(o,['unit_count','units','تعداد_واحد'])),parking_count:num(pick(o,['parking_count','parking','پارکینگ'])),storage_count:num(pick(o,['storage_count','storage','انباری'])),elevator:/^(1|true|yes|بله|دارد)$/i.test(String(pick(o,['elevator','آسانسور']))),regulation:pick(o,['regulation','ضوابط']),density:pick(o,['density','تراکم']),allowed_floors:pick(o,['allowed_floors','طبقات_مجاز']),occupancy_percent:num(pick(o,['occupancy_percent','occupancy','سطح_اشغال'])),setback:pick(o,['setback','عقب_نشینی']),total_price:num(pick(o,['total_price','price','قیمت','قیمت_کل'])),price_per_meter:num(pick(o,['price_per_meter','ppm','قیمت_متری'])),barter_possible:/^(1|true|yes|بله|دارد)$/i.test(String(pick(o,['barter_possible','barter','تهاتر']))),barter_details:pick(o,['barter_details','جزئیات_تهاتر']),payment_terms:pick(o,['payment_terms','شرایط_پرداخت']),owner_asking_price:num(pick(o,['owner_asking_price','قیمت_مالک'])),negotiable_price:num(pick(o,['negotiable_price','قیمت_قابل_مذاکره'])),mobile:pick(o,['mobile','phone','موبایل','تلفن']),owner_name:pick(o,['owner_name','owner','نام_مالک']),description:pick(o,['description','توضیحات']),internal_notes:pick(o,['internal_notes','یادداشت_داخلی']),status:pick(o,['status','وضعیت'])||'active'}}
function mapLead(o){return {full_name:pick(o,['full_name','name','نام','نام_خانوادگی']),mobile:pick(o,['mobile','phone','موبایل','تلفن']),desired_property_type:pick(o,['desired_property_type','property_type','نوع_ملک']),desired_region:num(pick(o,['desired_region','region','منطقه'])),budget_max:num(pick(o,['budget_max','budget','حداکثر_بودجه','بودجه'])),status:pick(o,['status','وضعیت'])||'active',notes:pick(o,['notes','یادداشت','توضیحات'])}}
function mapMarket(o){return {source_type:source==='excel'?'excel':'google_sheets',external_id:String(pick(o,['external_id','record_id','id','شناسه','کد'])||''),observed_at:pick(o,['observed_at','date','تاریخ'])||new Date().toISOString(),region:num(pick(o,['region','منطقه'])),neighborhood:pick(o,['neighborhood','محله']),property_type:pick(o,['property_type','نوع_ملک','نوع']),area:num(pick(o,['area','metrage','متراژ'])),bedrooms:num(pick(o,['bedrooms','خواب'])),age_years:num(pick(o,['age_years','age','سن_بنا'])),floor_number:num(pick(o,['floor_number','floor','طبقه'])),total_price:num(pick(o,['total_price','price','قیمت'])),price_per_meter:num(pick(o,['price_per_meter','ppm','قیمت_متری'])),listing_status:pick(o,['listing_status','status','وضعیت'])||'active',raw_payload:o}}
function preview(){var p=rows.slice(0,5).map(function(x){return target==='properties'?mapProperty(x):target==='leads'?mapLead(x):mapMarket(x)});document.getElementById('di-preview').innerHTML='<b>'+rows.length.toLocaleString('fa-IR')+' ردیف آماده است.</b> '+(rows.length>B?'در '+Math.ceil(rows.length/B)+' بخش ۱۰۰۰تایی وارد می‌شود.':'')+'<pre style="max-height:200px;overflow:auto;direction:ltr;text-align:left">'+E(JSON.stringify(p,null,2))+'</pre>';document.getElementById('di-run').disabled=!rows.length}
async function run(){var s=(await dbi.auth.getSession()).data.session;if(!s){alert('ابتدا وارد BuildWise AI شوید');return}var total=rows.length,ok=0,fail=0,imp=await dbi.from('import_batches').insert({file_name:source,total_rows:total,status:'running'}).select('id').single();document.getElementById('di-run').disabled=true;for(var i=0;i<total;i+=B){var c=rows.slice(i,i+B).map(function(x){return target==='properties'?mapProperty(x):target==='leads'?mapLead(x):mapMarket(x)}),sess=(await dbi.auth.getSession()).data.session,q=await fetch(U+'/functions/v1/crm-data-agent',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+sess.access_token},body:JSON.stringify({action:'import',target:target,rows:c})});if(q.ok){var jj=await q.json();if(jj.ok)ok+=c.length;else fail+=c.length}else fail+=c.length}if(imp.data)await dbi.from('import_batches').update({successful_rows:ok,failed_rows:fail,status:fail?'completed_with_errors':'completed'}).eq('id',imp.data.id);alert('BuildWise AI: '+ok+' رکورد موفق، '+fail+' خطا');closeModal();if(window.go)go(target==='properties'?'properties':target==='leads'?'leads':'market')}
function addNav(){['sideNav','mobileNav','bottomNav'].forEach(function(id){var n=document.getElementById(id);if(!n||document.getElementById('di-nav-'+id))return;var b=document.createElement('button');b.id='di-nav-'+id;b.className='nav-item';b.innerHTML='<i>⇧</i><span>ورود داده</span>';b.onclick=open;n.appendChild(b)})}
function start(){addNav();new MutationObserver(addNav).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();