/* BuildWise AI+H analysis engines. Pure calculation functions are shared by UI previews and API payloads. */
(function (global) {
  'use strict';
  const finite = value => Number.isFinite(Number(value)) ? Number(value) : 0;
  const median = values => { const sorted = values.map(finite).filter(value => value > 0).sort((a, b) => a - b); if (!sorted.length) return null; const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; };
  const clamp = (value, low, high) => Math.min(high, Math.max(low, value));
  function comparableWeight(subject, comparable, asOf) { const days = Math.max(0, (new Date(asOf) - new Date(comparable.observed_at || comparable.listed_at || asOf)) / 86400000); const areaDifference = subject.area > 0 ? Math.abs(finite(comparable.area) - subject.area) / subject.area : 0; const location = comparable.neighborhood === subject.neighborhood ? 1 : comparable.region === subject.region ? .65 : .2; const type = comparable.property_type === subject.property_type ? 1 : .35; return Math.exp(-days / 45) * Math.exp(-areaDifference * 1.5) * location * type; }
  function valueProperty(subject, observations, options) { const asOf = options?.asOf || new Date().toISOString(), maxAgeDays = finite(options?.maxAgeDays) || 62, adjustments = options?.adjustments || {}; const candidates = observations.filter(item => { const date = item.observed_at || item.listed_at; return date && finite(item.price_per_meter) > 0 && (new Date(asOf) - new Date(date)) / 86400000 <= maxAgeDays; }).map(item => { const weight = comparableWeight(subject, item, asOf); let adjusted = finite(item.price_per_meter); Object.keys(adjustments).forEach(key => { adjusted += (finite(subject[key]) - finite(item[key])) * finite(adjustments[key]); }); return Object.assign({}, item, { weight, adjusted_price_per_meter: adjusted }); }).filter(item => item.weight > .05); if (candidates.length < 3 || !finite(subject.area)) return { status: 'insufficient_data', comparable_count: candidates.length, comparables: candidates }; const totalWeight = candidates.reduce((sum, item) => sum + item.weight, 0), ppm = candidates.reduce((sum, item) => sum + item.adjusted_price_per_meter * item.weight, 0) / totalWeight, dispersion = median(candidates.map(item => Math.abs(item.adjusted_price_per_meter - ppm))) / ppm || 0, confidence = Math.round(clamp((candidates.length / 10) * 55 + (1 - clamp(dispersion, 0, 1)) * 35 + clamp(totalWeight / candidates.length, 0, 1) * 10, 5, 95)), spread = clamp(.025 + dispersion * 1.5 + (1 - confidence / 100) * .08, .04, .22); return { status: 'ready', comparable_count: candidates.length, price_per_meter: Math.round(ppm), estimated_value: Math.round(ppm * subject.area), low_value: Math.round(ppm * subject.area * (1 - spread)), high_value: Math.round(ppm * subject.area * (1 + spread)), confidence, comparables: candidates }; }
  function calculateConstruction(input, boq, priceBook) { const multiplier = finite(input.project_multiplier) || 1, prices = new Map((priceBook || []).map(item => [item.item_code, finite(item.unit_price)])), lines = (boq || []).map(line => { const quantity = finite(line.quantity), rate = finite(line.unit_rate) || prices.get(line.item_code) || 0; return Object.assign({}, line, { quantity, unit_rate: rate, amount: Math.round(quantity * rate) }); }), direct = lines.filter(line => line.cost_kind !== 'indirect').reduce((sum, line) => sum + line.amount, 0), indirect = direct * finite(input.indirect_percent) / 100 + lines.filter(line => line.cost_kind === 'indirect').reduce((sum, line) => sum + line.amount, 0), contingency = (direct + indirect) * finite(input.contingency_percent) / 100; return { lines, direct_cost: Math.round(direct), indirect_cost: Math.round(indirect), contingency: Math.round(contingency), total_before_multiplier: Math.round(direct + indirect + contingency), total_cost: Math.round((direct + indirect + contingency) * multiplier), multiplier }; }
  global.BuildWiseEngines = { valueProperty, calculateConstruction, median };
})(window);