/* Hooman AI — section-level contextual assistant */
(function(){
const U='https://beuestoewletjsgmigmf.supabase.co';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function token(){try{return (await window.db.auth.getSession()).data.session?.access_token||null}catch{return null}}
async function ask(p){const t=await token();if(!t)throw Error('ابتدا وارد BuildWise شوید.');const r=await fetch(U+'/functions/v1/ai-orchestrator',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify(p)});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||j.message||'پاسخ Hooman AI دریافت نشد');return j}
function context(s){return{title:s.dataset.aiTitle||s.querySelector('.card-title,h1,h2,h3')?.textContent?.trim()||'بخش',fields:[...s.querySelectorAll('input,select,textarea')].filter(x=>x.type!=='hidden').map(x=>({field:x.name||x.id||x.getAttribute('aria-label')||'',value:x.value})).filter(x=>x.field||x.value)}}
function panel(title,html){let x=document.getElementById('hw-ai-panel');if(!x){x=document.createElement('div');x.id='hw-ai-panel';document.body.appendChild(x)}x.innerHTML='<div class="hw-ai-card"><header><b>'+esc(title)+'</b><button type="button" onclick="this.closest(\'#hw-ai-panel\').remove()">×</button></header><div>'+html+'</div></div>'}
window.sectionAI=async s=>{const c=context(s);panel('Hooman AI · '+c.title,'<p class="muted">در حال بررسی این بخش…</p>');try{const j=await ask({action:'form_fill',message:'کل این بخش را بررسی کن. فقط پیشنهادها و تکمیل‌هایی را بده که از داده موجود با اطمینان کافی به دست می‌آیند؛ داده نامطمئن را تغییر نده.',context:c});const a=Array.isArray(j.fields)?j.fields:[];panel('Hooman AI · '+c.title,'<p>'+esc(j.note||j.text||'بررسی انجام شد.')+'</p>'+(a.length?'<div class="hw-ai-items">'+a.map(v=>'<div><b>'+esc(v.field||v.name||'مورد')+'</b><span>'+esc(v.value??v.suggestion??'')+'</span></div>').join('')+'</div>':'')+'<div class="hw-ai-actions"><button class="btn" onclick="this.closest(\'#hw-ai-panel\').remove()">بستن</button></div>')}catch(e){panel('Hooman AI','<p>'+esc(e.message)+'</p>')}}
function enhance(root=document){root.querySelectorAll('.card:not([data-hoomaan-ai-section]),[data-ai-section]:not([data-hoomaan-ai-section])').forEach(s=>{if(!s.matches('[data-ai-section]')&&!s.querySelector('input,select,textarea'))return;s.dataset.hoomaanAiSection='1';const h=s.querySelector('.card-title,h1,h2,h3')||s.firstElementChild;if(!h?.parentElement)return;const b=document.createElement('button');b.type='button';b.className='hoomaan-ai-section';b.textContent='Hooman AI';b.onclick=()=>sectionAI(s);h.parentElement.appendChild(b)})}
const css=document.createElement('style');css.textContent='.hoomaan-ai-section{float:left;border:1px solid #d7e3df;background:#f7faf9;color:#0d6657;border-radius:999px;padding:6px 11px;font-size:11px;font-weight:700}.hw-ai-card{position:fixed;left:18px;bottom:76px;z-index:10001;width:min(500px,calc(100vw - 36px));background:#fff;border:1px solid #dedbd3;border-radius:18px;padding:16px;box-shadow:0 20px 70px #0002}.hw-ai-card header{display:flex;justify-content:space-between}.hw-ai-card header button{border:0;background:none;font-size:22px}.hw-ai-items>div{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #eee}.hw-ai-items span{font-weight:700}.hw-ai-actions{display:flex;justify-content:flex-end;margin-top:14px}';document.head.appendChild(css);
const obs=new MutationObserver(()=>enhance());if(document.body)obs.observe(document.body,{childList:true,subtree:true});setTimeout(enhance,400);
})();