import { validateImportRows, buildImportPreview, applyColumnEdits, buildDataQualityDashboard } from './import-quality.js';
/* BuildWise AI — Canonical Data Importer (merged v1 + v2) */
(function(){
  const BN=window.BuildWiseNormalize||{};
  const U='https://beuestoewletjsgmigmf.supabase.co';
  const K='sb_publishable_dE92Qm9EtMv4sdNRXF7SRg_7ox1xYax';
  const dbi=supabase.createClient(U,K);
  const CHUNK=250; let rows=[],source='excel',target='properties',sourceFile='',importBatchId=null;
  const normalizePhone=BN.normalizePhone||((x)=>String(x??''));
  const E=x=>String(x==null?'':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const N=x=>BN.normalizeKey?BN.normalizeKey(x):String(x==null?'':x).trim().toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[\s\-\/]+/g,'_').replace(/[()]/g,'');
  const num=x=>BN.normalizeNumber?BN.normalizeNumber(x):(()=>{if(x===''||x==null)return null;const n=Number(String(x).replace(/[,٬]/g,''));return Number.isFinite(n)?n:null})();
  const pick=(o,a)=>{for(const k of a){const v=o[N(k)];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return ''};
  let xp;
  async function loadX(){if(window.XLSX)return; if(xp)return xp; xp=new Promise((ok,no)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://unpkg.com/xlsx@0.18.5/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(window.XLSX)return ok();if(i>=urls.length){xp=null;return no(Error('کتابخانه Excel بارگذاری نشد.'))}const s=document.createElement('script');s.src=urls[i++];s.onload=()=>window.XLSX?ok():next();s.onerror=next;document.head.appendChild(s)};next()});return xp}
  function mapProperty(o){return {property_code:String(pick(o,['property_code','code','کد','کد_ملک'])||('IMP-'+Date.now()+'-'+Math.random().toString(36).slice(2,8))),source:source,property_name:pick(o,['property_name','name','عنوان','نام'])||pick(o,['street','خیابان']),property_type:pick(o,['property_type','type','نوع_ملک','نوع']),request_type:pick(o,['request_type','نوع_درخواست']),region:num(pick(o,['region','zone','منطقه'])),neighborhood:pick(o,['neighborhood','area_name','محله']),street:pick(o,['street','خیابان']),land_area:num(pick(o,['land_area','land','زمین','مساحت_زمین'])),built_area:num(pick(o,['built_area','area','metrage','متراژ','زیربنا'])),bedrooms:num(pick(o,['bedrooms','rooms','خواب'])),total_price:num(pick(o,['total_price','price','قیمت','قیمت_کل'])),price_per_meter:num(pick(o,['price_per_meter','ppm','قیمت_متری'])),mobile:normalizePhone(pick(o,['mobile','phone','موبایل','تلفن'])),status:pick(o,['status','وضعیت'])||'active',description:pick(o,['description','توضیحات'])}};
  function mapLead(o){return {full_name:pick(o,['full_name','name','نام','نام_خانوادگی']),mobile:pick(o,['mobile','phone','موبایل','تلفن']),desired_property_type:pick(o,['desired_property_type','property_type','نوع_ملک']),desired_region:num(pick(o,['desired_region','region','منطقه'])),budget_min:num(pick(o,['budget_min','حداقل_بودجه'])),budget_max:num(pick(o,['budget_max','budget','حداکثر_بودجه','بودجه'])),status:pick(o,['status','وضعیت'])||'active',source:source,notes:pick(o,['notes','یادداشت','توضیحات'])}};
  function mapMarket(o){var area=num(pick(o,['area','metrage','متراژ'])),total=num(pick(o,['total_price','price','قیمت'])),ppm=num(pick(o,['price_per_meter','ppm','قیمت_متری']));if(ppm==null&&area>0&&total!=null)ppm=total/area;return {source_type:source==='excel'?'excel':'google_sheets',external_id:String(pick(o,['external_id','record_id','id','شناسه','کد'])||''),observed_at:pick(o,['observed_at','date','تاریخ'])||new Date().toISOString(),region:num(pick(o,['region','منطقه'])),neighborhood:pick(o,['neighborhood','محله']),property_type:pick(o,['property_type','نوع_ملک','نوع']),area:area,bedrooms:num(pick(o,['bedrooms','خواب'])),age_years:num(pick(o,['age_years','age','سن_بنا'])),floor_number:num(pick(o,['floor_number','floor','طبقه'])),total_price:total,price_per_meter:ppm,listing_status:pick(o,['listing_status','status','وضعیت'])||'active',raw_payload:o}};
function mapAny(o){return target==='properties'?mapProperty(o):target==='leads'?mapLead(o):mapMarket(o)}
function mapRows(){return rows.map(mapAny)}
  function quality(){return validateImportRows(rows)}
  function renderQuality(){const p=document.getElementById('bw-di-preview');if(!p)return;const q=quality();const d=buildDataQualityDashboard(rows);const preview=buildImportPreview(rows);p.innerHTML='<div class="card"><b>پیش‌نمایش و کنترل کیفیت</b><div>ردیف: '+preview.rowCount+' · ستون: '+preview.columnCount+' · معتبر: '+q.valid.length+' · خطادار: '+q.invalid.length+' · گروه تکراری: '+d.duplicateGroups+'</div><small>درصد خطا: '+(d.errorRate*100).toFixed(1)+'٪</small></div><div class="modal-actions"><button class="btn" onclick="window.__bwImportEdit()">ویرایش همه ستون‌ها</button></div><div style="overflow:auto"><table><thead><tr>'+preview.columns.map(E).map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+preview.sample.slice(0,20).map(r=>'<tr>'+preview.columns.map(k=>'<td>'+E(r[k])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'} 
  window.__bwImportEdit=function(){const p=document.getElementById('bw-di-preview');const cols=buildImportPreview(rows).columns;const sample=rows.slice(0,20);p.innerHTML='<div class="card"><b>ویرایش ستون‌ها</b><p>هر سلول واردشده قابل ویرایش است. تغییرات فقط روی داده فعلی اعمال می‌شود و نسخه خام حفظ می‌شود.</p><div style="overflow:auto"><table><thead><tr>'+cols.map(E).map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+sample.map((r,i)=>'<tr>'+cols.map(k=>'<td><input data-i="'+i+'" data-k="'+E(k)+'" value="'+E(r[k])+'"></td>').join('')+'</tr>').join('')+'</tbody></table></div><div class="modal-actions"><button class="btn" onclick="window.__bwImportQuality()">انصراف</button><button class="btn primary" onclick="window.__bwImportSaveEdits()">اعمال تغییرات</button></div></div>'};
  window.__bwImportSaveEdits=function(){const edits=[...document.querySelectorAll('#bw-di-preview input[data-i][data-k]')].map(x=>({rowIndex:Number(x.dataset.i),column:x.dataset.k,value:x.value}));rows=applyColumnEdits(rows,edits);window.__bwImportQuality()};
  window.__bwImportQuality=renderQuality;
  function sid(u){var m=String(u).match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);return m?m[1]:''}
function gid(u){var m=String(u).match(/[?&#]gid=(\d+)/);return m?m[1]:'0'}
function csv(t){var ls=t.split(/\r?\n/).filter(Boolean);if(!ls.length)return[];function p(s){var a=[],c='',q=false;for(var i=0;i<s.length;i++){var ch=s[i];if(ch==='"'){q=!q;continue}if(ch===','&&!q){a.push(c);c=''}else c+=ch}a.push(c);return a}var h=p(ls[0]),out=[];for(var j=1;j<ls.length;j++){var a=p(ls[j]),o={};h.forEach(function(k,i){o[k]=a[i]||''});out.push(o)}return out}
async function readRemote(){const p=document.getElementById('bw-di-preview');try{let u;if(source==='sheet'){var id=sid(document.getElementById('bw-di-url').value);if(!id)throw Error('لینک Google Sheet معتبر نیست');u='https://docs.google.com/spreadsheets/d/'+id+'/export?format=csv&gid='+gid(document.getElementById('bw-di-url').value)}else{u=document.getElementById('bw-di-bridge').value.replace(/\/$/,'')+'?action=sheet&sheet_id='+encodeURIComponent(document.getElementById('bw-di-id').value)+(document.getElementById('bw-di-gid').value?'&gid='+encodeURIComponent(document.getElementById('bw-di-gid').value):'')+'&token='+encodeURIComponent(document.getElementById('bw-di-token').value)}var r=await fetch(u);if(!r.ok)throw Error('Google پاسخ نداد');var t=await r.text();try{var j=JSON.parse(t);if(j.error)throw Error(j.error);rows=j.rows||[]}catch(_){rows=csv(t)}sourceFile=source==='sheet'?'google-sheet':'google-drive-bridge';rows=rows.map(function(x,i){return Object.assign({},x,{_sheet_name:'remote',_sheet_index:0,_row_number:i+2,_raw_data:x})});if(!rows.length)throw Error('داده‌ای پیدا نشد');p.innerHTML='<b>'+rows.length.toLocaleString('fa-IR')+' ردیف آماده است.</b><br>آرشیو خام رکوردها نیز ذخیره خواهد شد.';renderQuality();document.getElementById('bw-di-run').disabled=false}catch(e){p.innerHTML='<div class="errorbox">'+E(e.message||e)+'</div>'}}
  async function readFile(){const f=document.getElementById('bw-di-file')?.files?.[0];if(!f)return;sourceFile=f.name;const p=document.getElementById('bw-di-preview');p.innerHTML='در حال خواندن تمام شیت‌ها و ستون‌ها…';try{await loadX();const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});rows=[];wb.SheetNames.forEach((sheetName,sheetIndex)=>{const ws=wb.Sheets[sheetName];const data=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});data.forEach((raw,rowIndex)=>rows.push(Object.assign({},raw,{_sheet_name:sheetName,_sheet_index:sheetIndex,_row_number:rowIndex+2,_raw_data:raw})))});if(!rows.length)throw Error('هیچ ردیفی در هیچ شیتی پیدا نشد');const sheets=[...new Set(rows.map(x=>x._sheet_name))];p.innerHTML='<b>'+rows.length.toLocaleString('fa-IR')+' ردیف از '+sheets.length+' شیت آماده ورود است.</b><br>تمام ستون‌های هر شیت به‌صورت خام نیز ذخیره می‌شوند؛ علاوه بر فیلدهای استاندارد، هیچ ستون Excel حذف نمی‌شود.<br>ورود در بسته‌های ۲۵۰تایی انجام می‌شود.';renderQuality();document.getElementById('bw-di-run').disabled=false}catch(e){p.innerHTML='<div class="errorbox">'+E(e.message)+'</div>'}}
  function sourceBox(){source=document.getElementById('bw-di-source').value;var b=document.getElementById('bw-di-sourcebox');if(source==='excel'){b.innerHTML='<label>فایل Excel / CSV<input id="bw-di-file" type="file" accept=".xlsx,.xls,.csv"></label>';document.getElementById('bw-di-file').onchange=readFile}else if(source==='sheet'){b.innerHTML='<label>لینک Google Sheet<input id="bw-di-url" placeholder="https://docs.google.com/spreadsheets/d/..."></label><button id="bw-di-read" class="btn">خواندن</button>';document.getElementById('bw-di-read').onclick=readRemote}else{b.innerHTML='<label>Web App URL پل Google Drive<input id="bw-di-bridge" placeholder="https://script.google.com/macros/s/.../exec"></label><label>Bridge Token<input id="bw-di-token" type="password"></label><label>Spreadsheet ID<input id="bw-di-id"></label><label>GID اختیاری<input id="bw-di-gid" placeholder="0"></label><button id="bw-di-read" class="btn">خواندن Drive</button>';document.getElementById('bw-di-read').onclick=readRemote}}
  function open(){window.modal('<h2>ورود داده BuildWise AI</h2><p>Excel/CSV، Google Sheets و Google Drive Bridge. داده‌ها در بسته‌های ۲۵۰تایی وارد می‌شوند و بسته خراب به رکوردهای کوچک‌تر تقسیم می‌شود.</p><label>مقصد<select id="bw-di-target"><option value="properties">املاک</option><option value="leads">خواهان‌ها</option><option value="market">داده بازار</option></select></label><label>منبع<select id="bw-di-source"><option value="excel">Excel / CSV</option><option value="sheet">Google Sheets عمومی</option><option value="bridge">Google Drive Bridge</option></select></label><div id="bw-di-sourcebox"></div><div id="bw-di-preview"></div><div id="bw-di-result"></div><div class="modal-actions"><button class="btn" onclick="closeModal()">انصراف</button><button id="bw-di-run" class="btn primary" disabled>شروع ورود</button></div>');document.getElementById('bw-di-target').onchange=e=>target=e.target.value;document.getElementById('bw-di-source').onchange=sourceBox;sourceBox();document.getElementById('bw-di-run').onclick=run}

  async function sendBatch(batch){const s=(await dbi.auth.getSession()).data.session;if(!s)throw Error('ابتدا وارد BuildWise AI شوید');const payload=batch.map(mapAny);const r=await fetch(U+'/functions/v1/crm-data-agent',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.access_token},body:JSON.stringify({action:'import',target,rows:payload})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw Error(j.error||('HTTP '+r.status));return Number(j.processed??payload.length)}
  async function resilient(batch){try{return {ok:await sendBatch(batch),fail:[]}}catch(e){if(batch.length===1)return {ok:0,fail:[{row:batch[0],error:e.message}]};const m=Math.ceil(batch.length/2),a=await resilient(batch.slice(0,m)),b=await resilient(batch.slice(m));return {ok:a.ok+b.ok,fail:a.fail.concat(b.fail)}}}
  async function sendRaw(batch){const r=await dbi.from('import_raw_rows').insert(batch);if(r.error)throw r.error;return batch.length}
  async function resilientRaw(batch){try{return {ok:await sendRaw(batch),fail:[]}}catch(e){if(batch.length===1)return {ok:0,fail:[{row:batch[0],error:e.message}]};const m=Math.ceil(batch.length/2),a=await resilientRaw(batch.slice(0,m)),b=await resilientRaw(batch.slice(m));return {ok:a.ok+b.ok,fail:a.fail.concat(b.fail)}}}
  async function run(){const b=document.getElementById('bw-di-run'),res=document.getElementById('bw-di-result');const q=quality();if(q.invalid.length){renderQuality();toast('ورود متوقف شد: '+q.invalid.length+' ردیف نیازمند اصلاح است','error');return}b.disabled=true;let ok=0,failed=[],rawFailed=[];const session=(await dbi.auth.getSession()).data.session;if(!session){b.disabled=false;return toast('ابتدا وارد BuildWise AI شوید','error')}const created=await dbi.from('import_batches').insert({file_name:sourceFile||'Excel import',total_rows:rows.length,successful_rows:0,failed_rows:0,status:'processing'}).select('id').single();if(created.error){b.disabled=false;return toast(created.error.message,'error')}importBatchId=created.data.id;for(let i=0;i<rows.length;i+=CHUNK){const batch=rows.slice(i,i+CHUNK),r=await resilient(batch);ok+=r.ok;failed=failed.concat(r.fail);const raw=batch.map(x=>({import_batch_id:importBatchId,entity_type:target,source_file:sourceFile,sheet_name:x._sheet_name,sheet_index:x._sheet_index,row_number:x._row_number,raw_data:x._raw_data||{},normalized_data:mapAny(x)}));const rawResult=await resilientRaw(raw);rawFailed=rawFailed.concat(rawResult.fail);if(!rawResult.ok&&rawResult.fail.length===batch.length){res.innerHTML='<div>پیشرفت: '+Math.min(i+CHUNK,rows.length)+' / '+rows.length+'</div><div>موفق: '+ok+' · ناموفق استاندارد: '+failed.length+' · آرشیو خام ناموفق: '+rawResult.fail.length+'</div><div class="errorbox">رکوردهای استاندارد وارد شده‌اند؛ ذخیره آرشیو خام این بسته کامل نشد و جداگانه گزارش می‌شود.</div>'}else if(rawResult.fail.length){res.innerHTML='<div>پیشرفت: '+Math.min(i+CHUNK,rows.length)+' / '+rows.length+'</div><div>موفق: '+ok+' · ناموفق استاندارد: '+failed.length+' · آرشیو خام ناموفق: '+rawResult.fail.length+'</div><div>رکوردهای استاندارد و آرشیو خام به‌صورت مستقل مدیریت می‌شوند.</div>'}else res.innerHTML='<div>پیشرفت: '+Math.min(i+CHUNK,rows.length)+' / '+rows.length+'</div><div>موفق: '+ok+' · ناموفق: '+failed.length+'</div><div>تمام ستون‌های Excel نیز در آرشیو خام ذخیره می‌شوند.</div>'}const allErrors=failed.concat(rawFailed);await dbi.from('import_batches').update({successful_rows:ok,failed_rows:failed.length,status:failed.length?'completed_with_errors':'completed',error_log:allErrors.slice(0,50).map(x=>x.error).join('\n')||null}).eq('id',importBatchId);res.innerHTML='<div class="card"><b>نتیجه نهایی</b><p>کل: '+rows.length.toLocaleString('fa-IR')+' · موفق: '+ok.toLocaleString('fa-IR')+' · ناموفق: '+failed.length.toLocaleString('fa-IR')+'</p><p>شیت‌ها و تمام ستون‌های هر شیت نیز در آرشیو داده حفظ شده‌اند.</p>'+(failed.length?'<small>ردیف‌های ناموفق استاندارد نیازمند بررسی هستند.</small>':(rawFailed.length?'<small>رکوردهای استاندارد وارد شده‌اند؛ بخشی از آرشیو خام نیازمند بررسی است.</small>':'<strong>همه رکوردها و آرشیو خام با موفقیت وارد شدند.</strong>'))+'</div>';if(window.go)await go(target==='properties'?'properties':target==='leads'?'leads':'market');b.disabled=false}
  function addNav(){for(const id of ['sideNav','mobileNav','bottomNav']){const n=document.getElementById(id);if(!n||n.querySelector('#bw-di-nav'))continue;const b=document.createElement('button');b.id='bw-di-nav';b.className='nav-item';b.innerHTML='<i>⇧</i><span>ورود Excel</span>';b.onclick=open;n.appendChild(b)}}
  function start(){addNav();new MutationObserver(addNav).observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();