-- Applied Supabase migration: project_accounting_221_235
-- Tasks: 221 Forecast at Completion; 222 Cash Flow; 223 Receivables; 224 Payables;
-- 225 Contractor Payments; 226 Supplier Payments; 227 Advances; 228 Retention;
-- 229 Installments; 230 Payment Schedule; 231 Payment Approval;
-- 232 Invoice Upload; 233 Receipt Upload; 234 Document Archive; 235 Audit Trail.

create table if not exists public.project_financial_documents (
 id bigint generated by default as identity primary key, project_id bigint not null,
 document_type text not null check(document_type in ('invoice','receipt','other')),
 document_ref text, storage_path text, document_date date, amount numeric,
 currency text default 'TOMAN', metadata jsonb not null default '{}'::jsonb,
 uploaded_by uuid, created_at timestamptz not null default now());
create table if not exists public.project_payment_approvals (
 id bigint generated by default as identity primary key, project_id bigint not null,
 payment_id bigint, status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')),
 approved_by uuid, approved_at timestamptz, rejection_reason text, created_at timestamptz not null default now());
create table if not exists public.project_payment_schedule (
 id bigint generated by default as identity primary key, project_id bigint not null,
 commitment_id bigint, installment_no integer not null, due_date date not null,
 amount numeric not null check(amount>=0), retention_amount numeric not null default 0 check(retention_amount>=0),
 status text not null default 'scheduled', paid_at date, notes text,
 unique(project_id,commitment_id,installment_no));
create index if not exists idx_project_financial_documents_project on public.project_financial_documents(project_id,document_date desc);
create index if not exists idx_project_payment_approvals_project on public.project_payment_approvals(project_id,status);
create index if not exists idx_project_payment_schedule_project_due on public.project_payment_schedule(project_id,due_date);
alter table public.project_financial_documents enable row level security;
alter table public.project_payment_approvals enable row level security;
alter table public.project_payment_schedule enable row level security;
drop policy if exists buildwise_auth_all on public.project_financial_documents; create policy buildwise_auth_all on public.project_financial_documents for all to authenticated using(true) with check(true);
drop policy if exists buildwise_auth_all on public.project_payment_approvals; create policy buildwise_auth_all on public.project_payment_approvals for all to authenticated using(true) with check(true);
drop policy if exists buildwise_auth_all on public.project_payment_schedule; create policy buildwise_auth_all on public.project_payment_schedule for all to authenticated using(true) with check(true);

create or replace view public.project_forecast_at_completion with(security_invoker=true) as
select s.project_id,s.budget,s.revised_budget,s.actual_cost,s.committed_cost,s.forecast_cost,s.remaining_cost,
greatest(coalesce(s.actual_cost,0),0)+greatest(coalesce(s.remaining_cost,0),0) forecast_at_completion,
case when s.revised_budget=0 then null else ((greatest(coalesce(s.actual_cost,0),0)+greatest(coalesce(s.remaining_cost,0),0)-s.revised_budget)/s.revised_budget)*100 end forecast_variance_percent
from public.project_accounting_summary s;
create or replace view public.project_cash_flow with(security_invoker=true) as select project_id,entry_date flow_date,sum(debit-credit) net_cash_flow,sum(debit) inflow,sum(credit) outflow from public.project_ledger group by project_id,entry_date;
create or replace view public.project_receivables with(security_invoker=true) as select project_id,entry_date due_date,description,credit amount,currency,invoice_ref,case when entry_date<current_date then 'overdue' else 'open' end status from public.project_ledger where credit>0 and upper(coalesce(entry_type,'')) in ('RECEIVABLE','INCOME','SALE');
create or replace view public.project_payables with(security_invoker=true) as select c.project_id,c.id commitment_id,c.vendor_name payee,c.committed_amount,c.paid_amount,greatest(c.committed_amount-coalesce(c.paid_amount,0),0) outstanding_amount,c.due_date,c.status from public.project_commitments c where greatest(c.committed_amount-coalesce(c.paid_amount,0),0)>0;
create or replace view public.project_contractor_payments with(security_invoker=true) as select p.project_id,p.payee,p.amount,p.due_date,p.paid_at,p.status,p.reference_no from public.project_payments p where lower(coalesce(p.payment_type,''))='contractor';
create or replace view public.project_supplier_payments with(security_invoker=true) as select p.project_id,p.payee,p.amount,p.due_date,p.paid_at,p.status,p.reference_no from public.project_payments p where lower(coalesce(p.payment_type,''))='supplier';
create or replace view public.project_advance_payments with(security_invoker=true) as select p.project_id,p.payee,sum(p.amount) total_advance,count(*) payment_count from public.project_payments p where lower(coalesce(p.payment_type,''))='advance' group by p.project_id,p.payee;
create or replace view public.project_retention with(security_invoker=true) as select project_id,sum(retention_amount) retention_total,sum(case when due_date<current_date and status<>'paid' then retention_amount else 0 end) retention_due from public.project_commitments group by project_id;
create or replace view public.project_installments with(security_invoker=true) as select project_id,commitment_id,count(*) installment_count,sum(amount) scheduled_amount,sum(case when status='paid' then amount else 0 end) paid_amount,sum(case when status<>'paid' then amount else 0 end) outstanding_amount from public.project_payment_schedule group by project_id,commitment_id;
create or replace view public.project_payment_calendar with(security_invoker=true) as select project_id,due_date,sum(amount) scheduled_amount,sum(retention_amount) retention_amount,sum(case when status='paid' then amount else 0 end) paid_amount from public.project_payment_schedule group by project_id,due_date;
create or replace view public.project_invoice_archive with(security_invoker=true) as select * from public.project_financial_documents where document_type='invoice';
create or replace view public.project_receipt_archive with(security_invoker=true) as select * from public.project_financial_documents where document_type='receipt';
create or replace view public.project_accounting_audit with(security_invoker=true) as select l.id,l.project_id,l.entry_date,l.entry_type,l.description,l.debit,l.credit,l.currency,l.created_at,l.metadata from public.project_ledger l;