-- BuildWise AI — Project Accounting Tasks 201–220
alter table public.project_ledger add column if not exists usd_rate_toman numeric, add column if not exists gold18k_rate_toman_per_gram numeric;
create table if not exists public.project_accounting_rates (
 id bigint generated by default as identity primary key, rate_date date not null, usd_toman numeric not null check (usd_toman>0),
 gold18k_toman_per_gram numeric not null check (gold18k_toman_per_gram>0), source text, captured_at timestamptz not null default now(), unique(rate_date)
);
create table if not exists public.project_cost_indices (
 id bigint generated by default as identity primary key, index_date date not null, index_name text not null default 'construction_cost',
 index_value numeric not null check(index_value>0), source text, captured_at timestamptz not null default now(), unique(index_date,index_name)
);
create index if not exists idx_project_accounting_rates_date on public.project_accounting_rates(rate_date desc);
create index if not exists idx_project_cost_indices_date on public.project_cost_indices(index_name,index_date desc);
alter table public.project_accounting_rates enable row level security;
alter table public.project_cost_indices enable row level security;
drop policy if exists buildwise_auth_all on public.project_accounting_rates;
create policy buildwise_auth_all on public.project_accounting_rates for all to authenticated using(true) with check(true);
drop policy if exists buildwise_auth_all on public.project_cost_indices;
create policy buildwise_auth_all on public.project_cost_indices for all to authenticated using(true) with check(true);

create or replace view public.project_cost_by_wbs with(security_invoker=true) as select project_id,wbs_id,sum(debit-credit) net_cost from public.project_ledger where wbs_id is not null group by project_id,wbs_id;
create or replace view public.project_cost_by_phase with(security_invoker=true) as select project_id,phase_id,sum(debit-credit) net_cost from public.project_ledger where phase_id is not null group by project_id,phase_id;
create or replace view public.project_cost_by_floor with(security_invoker=true) as select project_id,floor_id,sum(debit-credit) net_cost from public.project_ledger where floor_id is not null group by project_id,floor_id;
create or replace view public.project_cost_by_unit with(security_invoker=true) as select project_id,unit_id,sum(debit-credit) net_cost from public.project_ledger where unit_id is not null group by project_id,unit_id;
create or replace view public.project_cost_by_contractor with(security_invoker=true) as select project_id,contractor_name,sum(debit-credit) net_cost from public.project_ledger where nullif(trim(contractor_name),'') is not null group by project_id,contractor_name;
create or replace view public.project_cost_by_supplier with(security_invoker=true) as select project_id,supplier_name,sum(debit-credit) net_cost from public.project_ledger where nullif(trim(supplier_name),'') is not null group by project_id,supplier_name;
create or replace view public.project_cost_by_material with(security_invoker=true) as select project_id,material_key,sum(debit-credit) net_cost from public.project_ledger where nullif(trim(material_key),'') is not null group by project_id,material_key;
create or replace view public.project_cost_by_purchase with(security_invoker=true) as select project_id,purchase_id,sum(debit-credit) net_cost from public.project_ledger where purchase_id is not null group by project_id,purchase_id;
create or replace view public.project_cost_by_invoice with(security_invoker=true) as select project_id,invoice_ref,sum(debit-credit) net_cost from public.project_ledger where nullif(trim(invoice_ref),'') is not null group by project_id,invoice_ref;
create or replace view public.project_cost_by_payment with(security_invoker=true) as select project_id,payment_id,sum(debit-credit) net_cost from public.project_ledger where payment_id is not null group by project_id,payment_id;
create or replace view public.project_cost_by_date with(security_invoker=true) as select project_id,entry_date,sum(debit-credit) net_cost from public.project_ledger group by project_id,entry_date;

create or replace view public.project_accounting_currency with(security_invoker=true) as
select l.id,l.project_id,l.entry_date,l.currency,l.debit,l.credit,(l.debit-l.credit) signed_amount,
case when upper(l.currency)='IRR' then (l.debit-l.credit)/10 when upper(l.currency)='TOMAN' then l.debit-l.credit when upper(l.currency)='USD' then (l.debit-l.credit)*coalesce(l.usd_rate_toman,r.usd_toman,0) else 0 end amount_toman,
case when upper(l.currency)='USD' then l.debit-l.credit when upper(l.currency)='IRR' then ((l.debit-l.credit)/10)/nullif(coalesce(l.usd_rate_toman,r.usd_toman),0) when upper(l.currency)='TOMAN' then (l.debit-l.credit)/nullif(coalesce(l.usd_rate_toman,r.usd_toman),0) else 0 end amount_usd,
case when upper(l.currency)='IRR' then ((l.debit-l.credit)/10)/nullif(coalesce(l.gold18k_rate_toman_per_gram,r.gold18k_toman_per_gram),0) when upper(l.currency)='TOMAN' then (l.debit-l.credit)/nullif(coalesce(l.gold18k_rate_toman_per_gram,r.gold18k_toman_per_gram),0) when upper(l.currency)='USD' then ((l.debit-l.credit)*coalesce(l.usd_rate_toman,r.usd_toman))/nullif(coalesce(l.gold18k_rate_toman_per_gram,r.gold18k_toman_per_gram),0) else 0 end amount_gold18k_grams,
r.usd_toman historical_usd_toman,r.gold18k_toman_per_gram historical_gold18k_toman_per_gram
from public.project_ledger l left join public.project_accounting_rates r on r.rate_date=l.entry_date;

create or replace view public.project_accounting_current_equivalent with(security_invoker=true) as
select c.*,cur.usd_toman current_usd_toman,cur.gold18k_toman_per_gram current_gold18k_toman_per_gram,
case when c.amount_toman is null then 0 else c.amount_toman/nullif(cur.usd_toman,0) end current_value_usd,
case when c.amount_toman is null then 0 else c.amount_toman/nullif(cur.gold18k_toman_per_gram,0) end current_value_gold18k_grams
from public.project_accounting_currency c
left join lateral(select usd_toman,gold18k_toman_per_gram from public.project_accounting_rates order by rate_date desc limit 1) cur on true;

create or replace view public.project_cost_inflation with(security_invoker=true) as
select c.id,c.project_id,c.entry_date,c.signed_amount,c.currency,i.index_value entry_index,latest.index_value latest_index,
case when i.index_value is null or latest.index_value is null then null else ((latest.index_value/i.index_value)-1)*100 end inflation_percent
from public.project_accounting_currency c
left join lateral(select index_value from public.project_cost_indices x where x.index_name='construction_cost' and x.index_date<=c.entry_date order by x.index_date desc limit 1)i on true
left join lateral(select index_value from public.project_cost_indices x where x.index_name='construction_cost' order by x.index_date desc limit 1)latest on true;

create or replace view public.project_accounting_variance with(security_invoker=true) as
select s.*, (s.revised_budget-s.actual_cost) budget_vs_actual_amount,
case when s.revised_budget=0 then null else ((s.actual_cost-s.revised_budget)/s.revised_budget)*100 end budget_vs_actual_percent,
(s.committed_cost-s.actual_cost) committed_vs_actual_amount,
case when s.actual_cost=0 then null else ((s.committed_cost-s.actual_cost)/s.actual_cost)*100 end committed_vs_actual_percent,
(s.forecast_cost-s.revised_budget) forecast_vs_budget_amount,
case when s.revised_budget=0 then null else ((s.forecast_cost-s.revised_budget)/s.revised_budget)*100 end forecast_vs_budget_percent
from public.project_accounting_summary s;
