alter table public.project_procurement
  add column if not exists approval_status text not null default 'not_required',
  add column if not exists approved_at timestamptz,
  add column if not exists purchase_order_id bigint,
  add column if not exists received_quantity numeric not null default 0,
  add column if not exists rejected_quantity numeric not null default 0,
  add column if not exists purchase_price_toman numeric not null default 0,
  add column if not exists purchase_price_usd numeric not null default 0,
  add column if not exists purchase_price_at timestamptz,
  add column if not exists purchase_price_source text,
  add column if not exists purchase_price_source_url text,
  add column if not exists purchase_price_timestamp timestamptz,
  add column if not exists current_price_toman numeric not null default 0,
  add column if not exists current_price_usd numeric not null default 0,
  add column if not exists current_price_timestamp timestamptz,
  add column if not exists current_price_source text,
  add column if not exists price_variance_toman numeric not null default 0,
  add column if not exists price_variance_percent numeric not null default 0,
  add column if not exists forecast_required_date date,
  add column if not exists forecast_quantity numeric not null default 0,
  add column if not exists recommended_purchase_date date,
  add column if not exists procurement_risk_score numeric not null default 0,
  add column if not exists procurement_risk_level text not null default 'low';

create table if not exists public.project_purchase_approvals (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.construction_projects(id) on delete cascade,
  procurement_id bigint not null references public.project_procurement(id) on delete cascade,
  requested_by uuid references auth.users(id),
  decided_by uuid references auth.users(id),
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.project_purchase_orders (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.construction_projects(id) on delete cascade,
  procurement_id bigint references public.project_procurement(id) on delete set null,
  po_number text not null,
  supplier_name text,
  ordered_at date,
  expected_delivery_at date,
  status text not null default 'draft' check (status in ('draft','submitted','confirmed','partially_received','received','cancelled')),
  quantity numeric not null default 0,
  unit text,
  unit_price_toman numeric not null default 0,
  total_price_toman numeric generated always as (quantity * unit_price_toman) stored,
  currency text not null default 'IRR',
  notes text,
  created_at timestamptz not null default now(),
  unique(project_id, po_number)
);

create table if not exists public.project_procurement_deliveries (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.construction_projects(id) on delete cascade,
  procurement_id bigint not null references public.project_procurement(id) on delete cascade,
  purchase_order_id bigint references public.project_purchase_orders(id) on delete set null,
  delivered_at date not null default current_date,
  quantity numeric not null default 0,
  accepted_quantity numeric not null default 0,
  rejected_quantity numeric not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  check (quantity >= 0 and accepted_quantity >= 0 and rejected_quantity >= 0),
  check (accepted_quantity + rejected_quantity <= quantity)
);

create table if not exists public.project_material_inventory (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.construction_projects(id) on delete cascade,
  material_key text not null,
  material_name text not null,
  unit text,
  on_hand_quantity numeric not null default 0,
  reserved_quantity numeric not null default 0,
  reorder_point numeric not null default 0,
  last_counted_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(project_id, material_key)
);

create table if not exists public.project_material_consumption (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.construction_projects(id) on delete cascade,
  material_inventory_id bigint references public.project_material_inventory(id) on delete set null,
  procurement_id bigint references public.project_procurement(id) on delete set null,
  boq_item_id bigint references public.project_boq_items(id) on delete set null,
  consumed_at date not null default current_date,
  quantity numeric not null default 0,
  unit text,
  source text not null default 'manual',
  notes text,
  created_at timestamptz not null default now(),
  check (quantity >= 0)
);

create table if not exists public.project_material_prices (
  id bigint generated by default as identity primary key,
  material_key text not null,
  material_name text not null,
  unit text,
  price_toman numeric not null default 0,
  price_usd numeric not null default 0,
  effective_at timestamptz not null default now(),
  source text not null,
  source_url text,
  captured_at timestamptz not null default now(),
  is_live boolean not null default false,
  notes text
);

create index if not exists idx_project_procurement_project_status on public.project_procurement(project_id,status);
create index if not exists idx_purchase_approvals_procurement on public.project_purchase_approvals(procurement_id,status);
create index if not exists idx_purchase_orders_procurement on public.project_purchase_orders(procurement_id);
create index if not exists idx_deliveries_procurement on public.project_procurement_deliveries(procurement_id,delivered_at);
create index if not exists idx_material_consumption_project_date on public.project_material_consumption(project_id,consumed_at);
create index if not exists idx_material_prices_key_effective on public.project_material_prices(material_key,effective_at desc);

alter table public.project_purchase_approvals enable row level security;
alter table public.project_purchase_orders enable row level security;
alter table public.project_procurement_deliveries enable row level security;
alter table public.project_material_inventory enable row level security;
alter table public.project_material_consumption enable row level security;
alter table public.project_material_prices enable row level security;

drop policy if exists buildwise_auth_all on public.project_purchase_approvals;
create policy buildwise_auth_all on public.project_purchase_approvals for all to authenticated using (true) with check (true);
drop policy if exists buildwise_auth_all on public.project_purchase_orders;
create policy buildwise_auth_all on public.project_purchase_orders for all to authenticated using (true) with check (true);
drop policy if exists buildwise_auth_all on public.project_procurement_deliveries;
create policy buildwise_auth_all on public.project_procurement_deliveries for all to authenticated using (true) with check (true);
drop policy if exists buildwise_auth_all on public.project_material_inventory;
create policy buildwise_auth_all on public.project_material_inventory for all to authenticated using (true) with check (true);
drop policy if exists buildwise_auth_all on public.project_material_consumption;
create policy buildwise_auth_all on public.project_material_consumption for all to authenticated using (true) with check (true);
drop policy if exists buildwise_auth_all on public.project_material_prices;
create policy buildwise_auth_all on public.project_material_prices for all to authenticated using (true) with check (true);

create or replace view public.project_procurement_control
with (security_invoker=true) as
select p.*,
coalesce(p.quantity,0)-coalesce(p.received_quantity,0)-coalesce(p.rejected_quantity,0) outstanding_quantity,
case when coalesce(p.quantity,0)>0 then round((coalesce(p.received_quantity,0)/p.quantity)*100,2) else 0 end delivery_percent,
case when coalesce(p.purchase_price_toman,0)>0 then round(((coalesce(p.current_price_toman,0)-p.purchase_price_toman)/p.purchase_price_toman)*100,2) else 0 end live_price_variance_percent,
case when coalesce(p.procurement_risk_score,0)>=75 then 'critical'
when coalesce(p.procurement_risk_score,0)>=50 then 'high'
when coalesce(p.procurement_risk_score,0)>=25 then 'medium' else 'low' end calculated_risk_level
from public.project_procurement p;