-- BuildWise AI — Customer Experience C01-C40 persistence
-- Extends canonical customer/portal/security domains; no parallel customer engine.

create table if not exists public.customer_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  crm_person_id bigint references public.crm_people(id) on delete set null,
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_requirements (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.crm_people(id) on delete cascade,
  intent text not null default 'general',
  requirements jsonb not null default '{}'::jsonb,
  missing_fields jsonb not null default '[]'::jsonb,
  status text not null default 'collecting' check (status in ('collecting','ready','matched','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_location_recommendations (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.crm_people(id) on delete cascade,
  location_name text not null,
  rank smallint not null check (rank between 1 and 4),
  score numeric not null default 0,
  price_tier text,
  evidence jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_interactions (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.crm_people(id) on delete cascade,
  entity_type text not null,
  entity_id bigint not null,
  interaction_type text not null,
  verified boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create table if not exists public.customer_ratings (
  id bigint generated by default as identity primary key,
  interaction_id bigint not null references public.customer_interactions(id) on delete cascade,
  customer_id bigint references public.crm_people(id) on delete cascade,
  entity_type text not null,
  entity_id bigint not null,
  rating_kind text not null default 'overall',
  score smallint not null check (score between 1 and 5),
  comment text not null default '',
  created_at timestamptz not null default now(),
  unique (interaction_id, rating_kind)
);

create table if not exists public.customer_experience_proposals (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.crm_people(id) on delete cascade,
  entity_type text not null,
  entity_id bigint not null,
  customer_estimate numeric,
  price_min numeric,
  price_max numeric,
  evidence jsonb not null default '[]'::jsonb,
  roi jsonb not null default '{}'::jsonb,
  scenario jsonb not null default '{}'::jsonb,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists customer_requirements_customer_idx on public.customer_requirements(customer_id,created_at desc);
create index if not exists customer_location_recommendations_customer_idx on public.customer_location_recommendations(customer_id,rank);
create index if not exists customer_interactions_entity_idx on public.customer_interactions(entity_type,entity_id,occurred_at desc);
create index if not exists customer_ratings_entity_idx on public.customer_ratings(entity_type,entity_id,created_at desc);
create index if not exists customer_proposals_customer_idx on public.customer_experience_proposals(customer_id,created_at desc);

alter table public.customer_profiles enable row level security;
alter table public.customer_requirements enable row level security;
alter table public.customer_location_recommendations enable row level security;
alter table public.customer_interactions enable row level security;
alter table public.customer_ratings enable row level security;
alter table public.customer_experience_proposals enable row level security;

drop policy if exists customer_profiles_owner on public.customer_profiles;
create policy customer_profiles_owner on public.customer_profiles
for all to authenticated
using (public.is_manager_user() or user_id=auth.uid())
with check (public.is_manager_user() or user_id=auth.uid());

drop policy if exists customer_requirements_owner on public.customer_requirements;
create policy customer_requirements_owner on public.customer_requirements
for all to authenticated
using (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_requirements.customer_id and p.user_id=auth.uid())
)
with check (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_requirements.customer_id and p.user_id=auth.uid())
);

drop policy if exists customer_location_recommendations_owner on public.customer_location_recommendations;
create policy customer_location_recommendations_owner on public.customer_location_recommendations
for all to authenticated
using (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_location_recommendations.customer_id and p.user_id=auth.uid())
)
with check (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_location_recommendations.customer_id and p.user_id=auth.uid())
);

drop policy if exists customer_interactions_owner on public.customer_interactions;
create policy customer_interactions_owner on public.customer_interactions
for all to authenticated
using (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_interactions.customer_id and p.user_id=auth.uid())
)
with check (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_interactions.customer_id and p.user_id=auth.uid())
);

drop policy if exists customer_ratings_owner on public.customer_ratings;
create policy customer_ratings_owner on public.customer_ratings
for all to authenticated
using (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_ratings.customer_id and p.user_id=auth.uid())
)
with check (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_ratings.customer_id and p.user_id=auth.uid())
);

drop policy if exists customer_proposals_owner on public.customer_experience_proposals;
create policy customer_proposals_owner on public.customer_experience_proposals
for all to authenticated
using (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_experience_proposals.customer_id and p.user_id=auth.uid())
)
with check (
  public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_experience_proposals.customer_id and p.user_id=auth.uid())
);

-- Only verified interactions may produce public ratings.
create or replace function public.customer_rating_is_verified()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $function$
begin
  if not exists (
    select 1 from public.customer_interactions i
    where i.id=new.interaction_id and i.verified=true
      and i.customer_id=new.customer_id
      and i.entity_type=new.entity_type
      and i.entity_id=new.entity_id
  ) then
    raise exception 'verified_interaction_required';
  end if;
  return new;
end;
$function$;

drop trigger if exists customer_rating_verified_guard on public.customer_ratings;
create trigger customer_rating_verified_guard
before insert or update on public.customer_ratings
for each row execute function public.customer_rating_is_verified();

create or replace function public.customer_price_range(p_estimate numeric, p_tolerance numeric default 0.05)
returns jsonb
language sql
immutable
security invoker
as $function$
  select jsonb_build_object(
    'estimate',p_estimate,
    'min',p_estimate*(1-least(greatest(coalesce(p_tolerance,0.05),0),0.05)),
    'max',p_estimate*(1+least(greatest(coalesce(p_tolerance,0.05),0),0.05)),
    'tolerance_pct',least(greatest(coalesce(p_tolerance,0.05),0),0.05)*100
  )
$function$;

create or replace view public.customer_rating_aggregation
with (security_invoker=true)
as
select
  entity_type,
  entity_id,
  count(*) filter (where i.verified) as verified_count,
  round(avg(r.score) filter (where i.verified),2) as average_score,
  round((avg(r.score) filter (where i.verified))*20,2) as market_score
from public.customer_ratings r
join public.customer_interactions i on i.id=r.interaction_id
group by entity_type,entity_id;

create or replace view public.customer_verified_reviews
with (security_invoker=true)
as
select r.id,r.entity_type,r.entity_id,r.rating_kind,r.score,r.comment,r.created_at
from public.customer_ratings r
join public.customer_interactions i on i.id=r.interaction_id
where i.verified=true;

-- Reuse the canonical field-policy table for the customer privacy firewall.
insert into public.security_field_policies(entity_type,field_name,visibility,roles,mask_strategy,active)
select 'customer','owner_phone','never',array[]::text[],'none',true
where not exists(select 1 from public.security_field_policies where entity_type='customer' and field_name='owner_phone');

insert into public.security_field_policies(entity_type,field_name,visibility,roles,mask_strategy,active)
select 'customer','internal_price','never',array[]::text[],'none',true
where not exists(select 1 from public.security_field_policies where entity_type='customer' and field_name='internal_price');

insert into public.security_field_policies(entity_type,field_name,visibility,roles,mask_strategy,active)
select 'customer','internal_notes','never',array[]::text[],'none',true
where not exists(select 1 from public.security_field_policies where entity_type='customer' and field_name='internal_notes');

insert into public.security_field_policies(entity_type,field_name,visibility,roles,mask_strategy,active)
select 'customer','negotiation','never',array[]::text[],'none',true
where not exists(select 1 from public.security_field_policies where entity_type='customer' and field_name='negotiation');
