create table if not exists public.project_ai_change_approvals (
 id bigint generated by default as identity primary key,
 project_id bigint not null references public.construction_projects(id) on delete cascade,
 recommendation_type text not null,
 recommendation jsonb not null default '{}'::jsonb,
 status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')),
 requested_at timestamptz not null default now(),
 decided_at timestamptz,
 requested_by uuid references auth.users(id),
 decided_by uuid references auth.users(id),
 decision_note text
);
alter table public.project_ai_change_approvals enable row level security;
drop policy if exists buildwise_auth_all on public.project_ai_change_approvals;
create policy buildwise_auth_all on public.project_ai_change_approvals for all to authenticated using(true) with check(true);