-- AI financial/procurement/sales intelligence, persistent memory and auditable action/explanation layer.
-- Reuses existing ai_audit_events and learning_events; no duplicate AI audit system.

create table if not exists public.ai_memory_entries (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  scope text not null default 'personal',
  title text not null,
  content text not null default '',
  tags text[] not null default '{}',
  source_type text not null default 'conversation',
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_action_runs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action_type text not null,
  payload jsonb not null default '{}'::jsonb,
  approval_status text not null default 'pending' check (approval_status in ('pending','approved','rejected')),
  execution_status text not null default 'pending' check (execution_status in ('pending','executed','failed','blocked')),
  result jsonb,
  error text,
  approved_at timestamptz,
  executed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_explanations (
  id bigint generated by default as identity primary key,
  action_run_id bigint references public.ai_action_runs(id) on delete set null,
  decision text,
  evidence jsonb not null default '[]'::jsonb,
  assumptions jsonb not null default '[]'::jsonb,
  risks jsonb not null default '[]'::jsonb,
  alternatives jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_memory_owner_idx on public.ai_memory_entries(owner_id,updated_at desc);
create index if not exists ai_memory_scope_idx on public.ai_memory_entries(scope,updated_at desc);
create index if not exists ai_action_runs_actor_idx on public.ai_action_runs(actor_id,created_at desc);
create index if not exists ai_action_runs_status_idx on public.ai_action_runs(execution_status,created_at desc);
create index if not exists ai_explanations_action_idx on public.ai_explanations(action_run_id,created_at desc);

alter table public.ai_memory_entries enable row level security;
alter table public.ai_action_runs enable row level security;
alter table public.ai_explanations enable row level security;

drop policy if exists ai_memory_owner_access on public.ai_memory_entries;
create policy ai_memory_owner_access on public.ai_memory_entries
for all to authenticated
using (owner_id=auth.uid() or public.is_manager_user())
with check (owner_id=auth.uid() or public.is_manager_user());

drop policy if exists ai_action_runs_access on public.ai_action_runs;
create policy ai_action_runs_access on public.ai_action_runs
for all to authenticated
using (actor_id=auth.uid() or public.is_manager_user())
with check (actor_id=auth.uid() or public.is_manager_user());

drop policy if exists ai_explanations_access on public.ai_explanations;
create policy ai_explanations_access on public.ai_explanations
for all to authenticated
using (public.is_manager_user() or exists(select 1 from public.ai_action_runs r where r.id=ai_explanations.action_run_id and r.actor_id=auth.uid()))
with check (public.is_manager_user() or exists(select 1 from public.ai_action_runs r where r.id=ai_explanations.action_run_id and r.actor_id=auth.uid()));

create or replace view public.ai_action_control as
select
  r.id,r.actor_id,r.action_type,r.approval_status,r.execution_status,r.created_at,r.executed_at,
  e.decision,e.risks,e.alternatives
from public.ai_action_runs r
left join public.ai_explanations e on e.action_run_id=r.id;
