-- BuildWise AI security governance foundations 598-603.
create table if not exists public.security_field_policies (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  field_name text not null,
  visibility text not null default 'manager_only',
  roles text[] not null default array['owner','admin','manager'],
  mask_strategy text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(entity_type,field_name)
);
alter table public.security_field_policies enable row level security;
drop policy if exists security_field_policies_manager on public.security_field_policies;
create policy security_field_policies_manager on public.security_field_policies
for all to authenticated using (public.is_manager_user()) with check (public.is_manager_user());
revoke all on public.security_field_policies from anon, authenticated;
grant select,insert,update,delete on public.security_field_policies to authenticated;

insert into public.security_field_policies(entity_type,field_name,visibility,roles,mask_strategy)
values
 ('person','phone','manager_only',array['owner','admin','manager'],'none'),
 ('person','emergency_phone','manager_only',array['owner','admin','manager'],'none'),
 ('property','mobile','manager_only',array['owner','admin','manager'],'none'),
 ('property','emergency_phone','manager_only',array['owner','admin','manager'],'none')
on conflict(entity_type,field_name) do update
set visibility=excluded.visibility,roles=excluded.roles,mask_strategy=excluded.mask_strategy,updated_at=now();

create table if not exists public.agent_tool_permissions (
  id bigint generated by default as identity primary key,
  agent_key text not null,
  tool_key text not null,
  environment text not null default 'production',
  allowed boolean not null default false,
  requires_approval boolean not null default true,
  allowed_roles text[] not null default array['owner','admin','manager'],
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(agent_key,tool_key,environment)
);
alter table public.agent_tool_permissions enable row level security;
drop policy if exists agent_tool_permissions_manager on public.agent_tool_permissions;
create policy agent_tool_permissions_manager on public.agent_tool_permissions
for all to authenticated using (public.is_manager_user()) with check (public.is_manager_user());
revoke all on public.agent_tool_permissions from anon, authenticated;
grant select,insert,update,delete on public.agent_tool_permissions to authenticated;

create table if not exists public.production_action_approvals (
  id bigint generated by default as identity primary key,
  agent_key text not null,
  action_type text not null,
  target_type text,
  target_id text,
  requested_by uuid not null default auth.uid() references auth.users(id),
  approved_by uuid references auth.users(id),
  status text not null default 'pending' check (status in ('pending','approved','rejected','executed','expired')),
  payload jsonb not null default '{}'::jsonb,
  reason text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  executed_at timestamptz
);
alter table public.production_action_approvals enable row level security;
drop policy if exists production_action_approvals_insert on public.production_action_approvals;
create policy production_action_approvals_insert on public.production_action_approvals
for insert to authenticated
with check (requested_by = auth.uid() and status='pending');
drop policy if exists production_action_approvals_select on public.production_action_approvals;
create policy production_action_approvals_select on public.production_action_approvals
for select to authenticated
using (public.is_manager_user() or requested_by=auth.uid());
drop policy if exists production_action_approvals_update_manager on public.production_action_approvals;
create policy production_action_approvals_update_manager on public.production_action_approvals
for update to authenticated
using (public.is_manager_user()) with check (public.is_manager_user());
revoke all on public.production_action_approvals from anon, authenticated;
grant select,insert,update on public.production_action_approvals to authenticated;

create or replace view public.properties_client
with (security_invoker=true)
as
select id, property_code, source, rate, status, request_type, property_type, ownership_type,
usage_type, region, neighborhood, street, property_name, alley, side_street, plaque,
location_lat, location_lng, frontage, passage_width, land_area, built_area, floor, total_floors,
bedrooms, building_age, unit_count, parking_count, storage_count, elevator, regulation, density,
allowed_floors, occupancy_percent, setback, number_of_fronts, aggregation_possible, permit_status,
completion_status, total_price, price_per_meter, entry_price, full_deposit, deposit_amount, rent_amount,
barter_possible, barter_details, payment_terms, owner_asking_price, negotiable_price, owner_id,
description, owner_notes, internal_notes, created_at, updated_at, last_contact_at, next_followup_at,
created_by, updated_by, units_per_floor, width, title_status, convertible, alley_name, sub_alley,
entrance_info, year_registered, rating, activity_status, listing_type, owner_name
from public.properties;
revoke all on public.properties_client from anon;
grant select on public.properties_client to authenticated;