create table if not exists public.crm_followups (
 id bigint generated by default as identity primary key, assigned_to uuid, created_by uuid default auth.uid(),
 public_request_id bigint, lead_id bigint, property_id bigint, deal_id bigint,
 followup_type text not null default 'general', title text not null, due_at timestamptz not null,
 reminder_at timestamptz, priority text not null default 'normal', status text not null default 'open',
 notes text, completed_at timestamptz, created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb
);
create index if not exists crm_followups_assigned_due_idx on public.crm_followups(assigned_to,due_at,status);
create table if not exists public.crm_security_reports (
 id bigint generated by default as identity primary key, reporter_id uuid default auth.uid(),
 subject_advisor_id uuid, category text not null default 'other', severity text not null default 'medium',
 description text not null, related_property_id bigint, related_request_id bigint, related_lead_id bigint,
 evidence jsonb not null default '{}'::jsonb, status text not null default 'open', reviewed_by uuid,
 reviewed_at timestamptz, resolution_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists crm_security_reports_subject_idx on public.crm_security_reports(subject_advisor_id,status);
create table if not exists public.crm_access_events (
 id bigint generated by default as identity primary key, actor_id uuid default auth.uid(), actor_name text,
 event_type text not null, target_type text, target_id bigint, metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists crm_access_events_actor_idx on public.crm_access_events(actor_id,created_at);
alter table public.crm_followups enable row level security;
alter table public.crm_security_reports enable row level security;
alter table public.crm_access_events enable row level security;
drop policy if exists crm_followups_select on public.crm_followups;
create policy crm_followups_select on public.crm_followups for select to authenticated using (public.is_manager_user() or assigned_to=auth.uid() or created_by=auth.uid());
drop policy if exists crm_followups_insert on public.crm_followups;
create policy crm_followups_insert on public.crm_followups for insert to authenticated with check (created_by=auth.uid() and (assigned_to=auth.uid() or public.is_manager_user()));
drop policy if exists crm_followups_update on public.crm_followups;
create policy crm_followups_update on public.crm_followups for update to authenticated using (public.is_manager_user() or assigned_to=auth.uid() or created_by=auth.uid()) with check (public.is_manager_user() or assigned_to=auth.uid() or created_by=auth.uid());
drop policy if exists crm_security_reports_select on public.crm_security_reports;
create policy crm_security_reports_select on public.crm_security_reports for select to authenticated using (public.is_manager_user() or reporter_id=auth.uid());
drop policy if exists crm_security_reports_insert on public.crm_security_reports;
create policy crm_security_reports_insert on public.crm_security_reports for insert to authenticated with check (reporter_id=auth.uid());
drop policy if exists crm_security_reports_update on public.crm_security_reports;
create policy crm_security_reports_update on public.crm_security_reports for update to authenticated using (public.is_manager_user()) with check (public.is_manager_user());
drop policy if exists crm_access_events_select on public.crm_access_events;
create policy crm_access_events_select on public.crm_access_events for select to authenticated using (public.is_manager_user() or actor_id=auth.uid());
drop policy if exists crm_access_events_insert on public.crm_access_events;
create policy crm_access_events_insert on public.crm_access_events for insert to authenticated with check (actor_id=auth.uid());