-- BuildWise KPI Engine 324-342
-- Canonical KPI extension over project_kpi_snapshots; no duplicate KPI subsystem.

create table if not exists public.project_kpi_definitions (
 id bigint generated by default as identity primary key,
 project_id bigint references public.construction_projects(id) on delete cascade,
 code text not null, name text not null, category text not null,
 source_metric text not null, target numeric,
 weight numeric not null default 1 check(weight>=0), unit text,
 active boolean not null default true, config jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(project_id,code)
);
create table if not exists public.project_kpi_thresholds (
 id bigint generated by default as identity primary key,
 project_id bigint references public.construction_projects(id) on delete cascade,
 kpi_code text not null, warning_value numeric, critical_value numeric,
 direction text not null default 'higher_is_better'
   check(direction in ('higher_is_better','lower_is_better')),
 enabled boolean not null default true, created_at timestamptz not null default now(),
 unique(project_id,kpi_code)
);
create unique index if not exists project_kpi_snapshots_project_date_uq
 on public.project_kpi_snapshots(project_id,snapshot_date);
alter table public.project_kpi_definitions enable row level security;
alter table public.project_kpi_thresholds enable row level security;

create or replace view public.project_kpi_live as
with base as (
 select p.id project_id, coalesce(p.physical_progress,0)::numeric progress_kpi,
 coalesce(p.planned_progress,0)::numeric planned_progress,
 coalesce(p.actual_cost,0)::numeric actual_cost,
 coalesce(p.current_budget,p.baseline_budget,0)::numeric budget,
 (select count(*) from project_schedule_tasks t where t.project_id=p.id and t.status not in ('completed','done'))::numeric open_tasks,
 (select count(*) from project_schedule_tasks t where t.project_id=p.id and t.is_critical=true and t.status not in ('completed','done'))::numeric critical_open_tasks,
 (select count(*) from project_schedule_tasks t where t.project_id=p.id and t.planned_finish<current_date and t.status not in ('completed','done'))::numeric delay_count,
 (select count(*) from project_procurement x where x.project_id=p.id and x.required_at<current_date and x.status not in ('delivered','completed','closed'))::numeric procurement_delay_count,
 (select count(*) from project_procurement x where x.project_id=p.id)::numeric procurement_count,
 (select count(*) from project_procurement x where x.project_id=p.id and x.delivered_at is not null and x.required_at is not null and x.delivered_at<=x.required_at)::numeric ontime_procurement_count,
 (select count(*) from project_quality_checks q where q.project_id=p.id)::numeric quality_count,
 (select count(*) from project_quality_checks q where q.project_id=p.id and q.status in ('resolved','closed','complete','completed'))::numeric quality_resolved_count,
 (select count(*) from project_daily_logs d where d.project_id=p.id)::numeric daily_log_count,
 (select count(*) from project_daily_logs d where d.project_id=p.id and nullif(trim(coalesce(d.safety_notes,'')),'') is not null)::numeric safety_documented_count,
 (select count(*) from project_unit_sales u where u.project_id=p.id)::numeric unit_inventory_count,
 (select count(*) from project_unit_sales u where u.project_id=p.id and u.status='sold')::numeric sold_units,
 (select count(*) from project_payments x where x.project_id=p.id and lower(coalesce(x.payment_type,''))='contractor')::numeric contractor_payment_count,
 (select count(*) from project_payments x where x.project_id=p.id and lower(coalesce(x.payment_type,''))='contractor' and x.status in ('paid','completed'))::numeric contractor_paid_count,
 (select count(*) from project_procurement x where x.project_id=p.id and nullif(trim(coalesce(x.supplier_name,'')),'') is not null)::numeric supplier_order_count,
 (select count(*) from project_procurement x where x.project_id=p.id and nullif(trim(coalesce(x.supplier_name,'')),'') is not null and x.status in ('delivered','completed','closed'))::numeric supplier_delivered_count
 from construction_projects p)
select *, (progress_kpi-planned_progress) progress_variance,
 case when budget>0 then actual_cost/budget*100 else 0 end cost_consumption,
 case when daily_log_count>0 then safety_documented_count/daily_log_count*100 else 0 end hse_documentation_kpi,
 case when quality_count>0 then quality_resolved_count/quality_count*100 else 0 end quality_kpi,
 case when procurement_count>0 then ontime_procurement_count/procurement_count*100 else 0 end procurement_kpi,
 case when unit_inventory_count>0 then sold_units/unit_inventory_count*100 else 0 end unit_sales_kpi,
 case when contractor_payment_count>0 then contractor_paid_count/contractor_payment_count*100 else 0 end contractor_kpi,
 case when supplier_order_count>0 then supplier_delivered_count/supplier_order_count*100 else 0 end supplier_kpi,
 case when budget>0 then (actual_cost-budget)/budget*100 else 0 end cost_overrun_kpi,
 case when daily_log_count>0 then progress_kpi/daily_log_count else progress_kpi end productivity_kpi,
 case when actual_cost>0 and budget>0 then (budget-actual_cost)/actual_cost*100 else 0 end roi_cost_proxy_kpi
from base;

create or replace view public.project_kpi_catalog as
select project_id,'quality' kpi_code,'Quality KPI' kpi_name,quality_kpi value,'%' unit from project_kpi_live
union all select project_id,'hse','HSE KPI',hse_documentation_kpi,'% ' from project_kpi_live
union all select project_id,'sales','Sales KPI',unit_sales_kpi,'% ' from project_kpi_live
union all select project_id,'cash_flow','Cash Flow KPI',case when budget>0 then greatest(0,100-cost_consumption) else 0 end,'% ' from project_kpi_live
union all select project_id,'contractor','Contractor KPI',contractor_kpi,'% ' from project_kpi_live
union all select project_id,'supplier','Supplier KPI',supplier_kpi,'% ' from project_kpi_live
union all select project_id,'productivity','Productivity KPI',productivity_kpi,'progress/log' from project_kpi_live
union all select project_id,'progress','Progress KPI',progress_kpi,'% ' from project_kpi_live
union all select project_id,'delay','Delay KPI',delay_count,'count' from project_kpi_live
union all select project_id,'cost_overrun','Cost Overrun KPI',cost_overrun_kpi,'% ' from project_kpi_live
union all select project_id,'procurement_delay','Procurement Delay KPI',procurement_delay_count,'count' from project_kpi_live
union all select project_id,'unit_sales','Unit Sales KPI',unit_sales_kpi,'% ' from project_kpi_live
union all select project_id,'roi','ROI KPI',roi_cost_proxy_kpi,'% ' from project_kpi_live
union all select project_id,'profit_margin','Profit Margin KPI',coalesce((select avg(sp.margin_percent) from project_sales_profitability sp where sp.project_id=k.project_id),0),'% ' from project_kpi_live k;

create or replace view public.project_kpi_trends as
select s.project_id,s.snapshot_date,
 coalesce((s.schedule_kpi->>'progress')::numeric,0) progress,
 coalesce((s.schedule_kpi->>'delay_count')::numeric,0) delay_count,
 coalesce((s.cost_kpi->>'cost_consumption_percent')::numeric,0) cost_consumption_percent,
 coalesce((s.procurement_kpi->>'delay_count')::numeric,0) procurement_delay_count,
 coalesce((s.sales_kpi->>'sold_units')::numeric,0) sold_units,
 coalesce((s.overall_kpi->>'score')::numeric,0) overall_score
from project_kpi_snapshots s;

create or replace view public.project_kpi_drilldown as
select project_id,'schedule' domain,'open_tasks' metric,open_tasks value from project_kpi_live
union all select project_id,'schedule','critical_open_tasks',critical_open_tasks from project_kpi_live
union all select project_id,'schedule','delay_count',delay_count from project_kpi_live
union all select project_id,'cost','actual_cost',actual_cost from project_kpi_live
union all select project_id,'cost','budget',budget from project_kpi_live
union all select project_id,'cost','cost_overrun_percent',cost_overrun_kpi from project_kpi_live
union all select project_id,'procurement','delay_count',procurement_delay_count from project_kpi_live
union all select project_id,'procurement','ontime_percent',procurement_kpi from project_kpi_live
union all select project_id,'sales','inventory',unit_inventory_count from project_kpi_live
union all select project_id,'sales','sold_units',sold_units from project_kpi_live
union all select project_id,'quality','resolved_percent',quality_kpi from project_kpi_live
union all select project_id,'hse','documentation_percent',hse_documentation_kpi from project_kpi_live;

create or replace function public.refresh_project_kpi_snapshot(p_project_id bigint)
returns bigint language plpgsql security invoker as $$
declare sid bigint;
begin
 insert into project_kpi_snapshots(project_id,snapshot_date,schedule_kpi,cost_kpi,procurement_kpi,sales_kpi,overall_kpi)
 select project_id,current_date,
 jsonb_build_object('progress',progress_kpi,'planned_progress',planned_progress,'progress_variance',progress_variance,'delay_count',delay_count,'open_tasks',open_tasks,'critical_open_tasks',critical_open_tasks),
 jsonb_build_object('actual_cost',actual_cost,'budget',budget,'cost_consumption_percent',cost_consumption,'cost_overrun_percent',cost_overrun_kpi),
 jsonb_build_object('delay_count',procurement_delay_count,'ontime_percent',procurement_kpi),
 jsonb_build_object('inventory',unit_inventory_count,'sold_units',sold_units,'sold_percent',unit_sales_kpi),
 jsonb_build_object('score',greatest(0,least(100,(progress_kpi+procurement_kpi+quality_kpi+hse_documentation_kpi)/4)))
 from project_kpi_live where project_id=p_project_id
 on conflict(project_id,snapshot_date) do update set schedule_kpi=excluded.schedule_kpi,cost_kpi=excluded.cost_kpi,procurement_kpi=excluded.procurement_kpi,sales_kpi=excluded.sales_kpi,overall_kpi=excluded.overall_kpi
 returning id into sid;
 return sid;
end $$;

create or replace view public.project_kpi_alerts as
select k.project_id,k.kpi_code,k.kpi_name,k.value,k.unit,t.warning_value,t.critical_value,t.direction,
case when t.enabled and t.direction='higher_is_better' and t.critical_value is not null and k.value<t.critical_value then 'critical'
 when t.enabled and t.direction='higher_is_better' and t.warning_value is not null and k.value<t.warning_value then 'warning'
 when t.enabled and t.direction='lower_is_better' and t.critical_value is not null and k.value>t.critical_value then 'critical'
 when t.enabled and t.direction='lower_is_better' and t.warning_value is not null and k.value>t.warning_value then 'warning'
 else 'normal' end alert_level
from project_kpi_catalog k left join project_kpi_thresholds t on t.project_id=k.project_id and t.kpi_code=k.kpi_code;
