-- Advisor / request operations for checklist 386-400.
-- Reuses public_requests and crm_followups; these are control tables, not duplicate CRM entities.

create table if not exists public.advisor_request_assignments (
  id bigint generated by default as identity primary key,
  request_id bigint not null,
  advisor_id uuid not null references auth.users(id) on delete cascade,
  assigned_by uuid references auth.users(id) on delete set null,
  status text not null default 'assigned' check (status in ('assigned','accepted','rejected','transferred','closed')),
  assignment_reason text not null default '',
  assigned_at timestamptz not null default now(),
  responded_at timestamptz,
  transferred_from uuid references auth.users(id) on delete set null,
  transferred_to uuid references auth.users(id) on delete set null
);

create table if not exists public.advisor_request_responses (
  id bigint generated by default as identity primary key,
  request_id bigint not null,
  advisor_id uuid not null references auth.users(id) on delete cascade,
  response text not null check (response in ('accepted','rejected')),
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.advisor_promotions (
  id bigint generated by default as identity primary key,
  advisor_id uuid not null references auth.users(id) on delete cascade,
  item_type text not null,
  item_id bigint not null,
  reason text not null default '',
  status text not null default 'proposed' check (status in ('proposed','approved','rejected','expired')),
  promoted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  decided_at timestamptz
);

create table if not exists public.advisor_hot_slots (
  id bigint generated by default as identity primary key,
  advisor_id uuid not null references auth.users(id) on delete cascade,
  slot_at timestamptz not null,
  reason text not null default '',
  status text not null default 'proposed' check (status in ('proposed','approved','rejected','expired')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  decided_at timestamptz
);

create table if not exists public.advisor_kpi_snapshots (
  id bigint generated by default as identity primary key,
  advisor_id uuid not null references auth.users(id) on delete cascade,
  snapshot_at timestamptz not null default now(),
  request_count integer not null default 0,
  followup_count integer not null default 0,
  followup_completed integer not null default 0,
  response_count integer not null default 0,
  acceptance_rate_pct numeric not null default 0,
  workload_health_pct numeric not null default 0,
  customer_outcome_pct numeric not null default 0
);

create table if not exists public.advisor_scorecards (
  id bigint generated by default as identity primary key,
  advisor_id uuid not null references auth.users(id) on delete cascade,
  period_start date,
  period_end date,
  response_rate_pct numeric not null default 0,
  completion_rate_pct numeric not null default 0,
  workload_health_pct numeric not null default 0,
  customer_outcome_pct numeric not null default 0,
  score numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists advisor_assignment_request_idx on public.advisor_request_assignments(request_id, assigned_at desc);
create index if not exists advisor_assignment_advisor_idx on public.advisor_request_assignments(advisor_id, status);
create index if not exists advisor_response_request_idx on public.advisor_request_responses(request_id, created_at desc);
create index if not exists advisor_promotion_advisor_idx on public.advisor_promotions(advisor_id, status);
create index if not exists advisor_hot_slot_idx on public.advisor_hot_slots(advisor_id, slot_at);
create index if not exists advisor_kpi_idx on public.advisor_kpi_snapshots(advisor_id, snapshot_at desc);
create index if not exists advisor_scorecard_idx on public.advisor_scorecards(advisor_id, period_end desc);

alter table public.advisor_request_assignments enable row level security;
alter table public.advisor_request_responses enable row level security;
alter table public.advisor_promotions enable row level security;
alter table public.advisor_hot_slots enable row level security;
alter table public.advisor_kpi_snapshots enable row level security;
alter table public.advisor_scorecards enable row level security;

drop policy if exists advisor_assignment_access on public.advisor_request_assignments;
create policy advisor_assignment_access on public.advisor_request_assignments
for all to authenticated
using (advisor_id=auth.uid() or assigned_by=auth.uid() or public.is_manager_user())
with check (public.is_manager_user() or advisor_id=auth.uid());

drop policy if exists advisor_response_access on public.advisor_request_responses;
create policy advisor_response_access on public.advisor_request_responses
for all to authenticated
using (advisor_id=auth.uid() or public.is_manager_user())
with check (advisor_id=auth.uid() or public.is_manager_user());

drop policy if exists advisor_promotion_access on public.advisor_promotions;
create policy advisor_promotion_access on public.advisor_promotions
for all to authenticated
using (advisor_id=auth.uid() or promoted_by=auth.uid() or public.is_manager_user())
with check (public.is_manager_user());

drop policy if exists advisor_hot_slot_access on public.advisor_hot_slots;
create policy advisor_hot_slot_access on public.advisor_hot_slots
for all to authenticated
using (advisor_id=auth.uid() or created_by=auth.uid() or public.is_manager_user())
with check (advisor_id=auth.uid() or public.is_manager_user());

drop policy if exists advisor_kpi_access on public.advisor_kpi_snapshots;
create policy advisor_kpi_access on public.advisor_kpi_snapshots
for select to authenticated
using (advisor_id=auth.uid() or public.is_manager_user());

drop policy if exists advisor_scorecard_access on public.advisor_scorecards;
create policy advisor_scorecard_access on public.advisor_scorecards
for select to authenticated
using (advisor_id=auth.uid() or public.is_manager_user());

create or replace view public.advisor_operations_control as
select
  a.advisor_id,
  count(distinct a.id) filter (where a.status in ('assigned','accepted')) as active_requests,
  count(distinct r.id) filter (where r.response='accepted') as accepted_requests,
  count(distinct r.id) as response_count,
  count(distinct f.id) filter (where f.status='open') as open_followups,
  count(distinct f.id) filter (where f.status='completed') as completed_followups,
  count(distinct p.id) filter (where p.status in ('proposed','approved')) as promoted_items,
  count(distinct h.id) filter (where h.status in ('proposed','approved') and h.slot_at >= now()) as upcoming_hot_slots
from public.advisor_request_assignments a
left join public.advisor_request_responses r on r.advisor_id=a.advisor_id and r.request_id=a.request_id
left join public.crm_followups f on f.assigned_to=a.advisor_id
left join public.advisor_promotions p on p.advisor_id=a.advisor_id
left join public.advisor_hot_slots h on h.advisor_id=a.advisor_id
group by a.advisor_id;
