-- BuildWise Project HSE + Corrective Actions
-- Canonical live schema reconciliation: 2026-10-06

create table if not exists public.project_hse (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.construction_projects(id) on delete cascade,
  incident_type text not null default 'observation',
  title text not null,
  description text,
  severity text not null default 'medium',
  status text not null default 'open',
  occurred_at timestamptz,
  location text,
  reported_by uuid,
  assigned_to uuid,
  root_cause text,
  immediate_action text,
  lost_time_hours numeric not null default 0,
  recordable boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_hse_severity_chk check (severity in ('low','medium','high','critical')),
  constraint project_hse_status_chk check (status in ('open','investigating','action_required','closed'))
);

create table if not exists public.project_corrective_actions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.construction_projects(id) on delete cascade,
  hse_id bigint references public.project_hse(id) on delete set null,
  risk_id bigint references public.project_risks(id) on delete set null,
  title text not null,
  description text,
  priority text not null default 'medium',
  status text not null default 'open',
  assigned_to uuid,
  due_date date,
  completed_at timestamptz,
  verification_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_corrective_priority_chk check (priority in ('low','medium','high','critical')),
  constraint project_corrective_status_chk check (status in ('open','in_progress','blocked','completed','cancelled'))
);

create index if not exists idx_project_hse_project_status on public.project_hse(project_id,status);
create index if not exists idx_project_hse_project_severity on public.project_hse(project_id,severity);
create index if not exists idx_project_corrective_project_status on public.project_corrective_actions(project_id,status);
create index if not exists idx_project_corrective_due_date on public.project_corrective_actions(project_id,due_date);

alter table public.project_hse enable row level security;
alter table public.project_corrective_actions enable row level security;

create policy project_hse_authenticated_select on public.project_hse for select to authenticated using (true);
create policy project_hse_authenticated_write on public.project_hse for all to authenticated using (true) with check (true);
create policy project_corrective_authenticated_select on public.project_corrective_actions for select to authenticated using (true);
create policy project_corrective_authenticated_write on public.project_corrective_actions for all to authenticated using (true) with check (true);
