-- Customer presentation, request journey, notifications and appointments for checklist 406-415.
-- Reuses construction_projects, media registry, customer_shares and CRM people.

create table if not exists public.customer_experience_views (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.crm_people(id) on delete set null,
  project_id bigint,
  unit_id bigint,
  view_type text not null check (view_type in ('walkthrough','floor_plan','unit','proposal','roi')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_notifications (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.crm_people(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_appointments (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.crm_people(id) on delete set null,
  advisor_id uuid references auth.users(id) on delete set null,
  project_id bigint,
  unit_id bigint,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'requested' check (status in ('requested','confirmed','rescheduled','completed','cancelled','no_show')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customer_experience_views_customer_idx on public.customer_experience_views(customer_id,created_at desc);
create index if not exists customer_experience_views_project_idx on public.customer_experience_views(project_id,view_type);
create index if not exists customer_notifications_customer_idx on public.customer_notifications(customer_id,created_at desc);
create index if not exists customer_appointments_advisor_idx on public.customer_appointments(advisor_id,starts_at);
create index if not exists customer_appointments_customer_idx on public.customer_appointments(customer_id,starts_at);

alter table public.customer_experience_views enable row level security;
alter table public.customer_notifications enable row level security;
alter table public.customer_appointments enable row level security;

drop policy if exists customer_experience_view_access on public.customer_experience_views;
create policy customer_experience_view_access on public.customer_experience_views
for all to authenticated
using (public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_experience_views.customer_id and p.user_id=auth.uid()))
with check (public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_experience_views.customer_id and p.user_id=auth.uid()));

drop policy if exists customer_notification_access on public.customer_notifications;
create policy customer_notification_access on public.customer_notifications
for select to authenticated
using (public.is_manager_user() or exists(select 1 from public.crm_people p where p.id=customer_notifications.customer_id and p.user_id=auth.uid()));

drop policy if exists customer_appointment_access on public.customer_appointments;
create policy customer_appointment_access on public.customer_appointments
for all to authenticated
using (public.is_manager_user() or advisor_id=auth.uid() or exists(select 1 from public.crm_people p where p.id=customer_appointments.customer_id and p.user_id=auth.uid()))
with check (public.is_manager_user() or advisor_id=auth.uid() or exists(select 1 from public.crm_people p where p.id=customer_appointments.customer_id and p.user_id=auth.uid()));

create or replace view public.customer_appointment_control as
select
  a.id,a.customer_id,a.advisor_id,a.project_id,a.unit_id,a.starts_at,a.ends_at,a.status,
  case when a.starts_at < now() and a.status='requested' then 'overdue' else 'normal' end as timing_state
from public.customer_appointments a;
