-- Canonical contract control for checklist 377-385.
-- Extends the existing BuildWiseContract responsibility; no parallel contract engine.

create table if not exists public.contract_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  body text not null default '',
  variables jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('draft','active','archived')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contracts (
  id bigint generated by default as identity primary key,
  template_id bigint references public.contract_templates(id) on delete set null,
  deal_id bigint,
  project_id bigint,
  title text not null,
  subject text not null default '',
  consideration numeric not null default 0,
  status text not null default 'draft' check (status in ('draft','pending_approval','approved','pending_signature','signed','active','breached','closed','cancelled')),
  current_version integer not null default 1,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contract_versions (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  version integer not null,
  snapshot jsonb not null default '{}'::jsonb,
  change_note text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(contract_id, version)
);

create table if not exists public.contract_attachments (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  file_id bigint,
  title text not null default '',
  status text not null default 'active' check (status in ('active','superseded','removed')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.contract_approvals (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  approver_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  comment text not null default '',
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.contract_signatures (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  signer_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','signed','declined','void')),
  signature_ref text,
  signed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.contract_obligations (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  title text not null,
  amount numeric not null default 0,
  due_at timestamptz,
  status text not null default 'open' check (status in ('open','fulfilled','overdue','cancelled')),
  fulfilled_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.contract_milestones (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  title text not null,
  due_at timestamptz,
  status text not null default 'pending' check (status in ('pending','completed','overdue','cancelled')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.contract_breach_alerts (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  title text not null,
  severity text not null default 'medium' check (severity in ('low','medium','high','critical')),
  status text not null default 'open' check (status in ('open','acknowledged','resolved')),
  detected_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists contracts_deal_idx on public.contracts(deal_id);
create index if not exists contracts_project_idx on public.contracts(project_id);
create index if not exists contract_versions_contract_idx on public.contract_versions(contract_id, version desc);
create index if not exists contract_attachments_contract_idx on public.contract_attachments(contract_id);
create index if not exists contract_approvals_contract_idx on public.contract_approvals(contract_id, created_at desc);
create index if not exists contract_signatures_contract_idx on public.contract_signatures(contract_id, created_at desc);
create index if not exists contract_obligations_due_idx on public.contract_obligations(contract_id, due_at);
create index if not exists contract_milestones_due_idx on public.contract_milestones(contract_id, due_at);
create index if not exists contract_breach_alerts_open_idx on public.contract_breach_alerts(contract_id, status);

alter table public.contract_templates enable row level security;
alter table public.contracts enable row level security;
alter table public.contract_versions enable row level security;
alter table public.contract_attachments enable row level security;
alter table public.contract_approvals enable row level security;
alter table public.contract_signatures enable row level security;
alter table public.contract_obligations enable row level security;
alter table public.contract_milestones enable row level security;
alter table public.contract_breach_alerts enable row level security;

drop policy if exists contract_manager_all on public.contracts;
create policy contract_manager_all on public.contracts
for all to authenticated
using (exists (select 1 from public.app_roles r where r.user_id=auth.uid() and r.active=true and r.role in ('owner','admin','manager')))
with check (exists (select 1 from public.app_roles r where r.user_id=auth.uid() and r.active=true and r.role in ('owner','admin','manager')));

drop policy if exists contract_template_manager_all on public.contract_templates;
create policy contract_template_manager_all on public.contract_templates
for all to authenticated
using (exists (select 1 from public.app_roles r where r.user_id=auth.uid() and r.active=true and r.role in ('owner','admin','manager')))
with check (exists (select 1 from public.app_roles r where r.user_id=auth.uid() and r.active=true and r.role in ('owner','admin','manager')));

do $$
declare t text;
begin
  foreach t in array array[
    'contract_versions','contract_attachments','contract_approvals',
    'contract_signatures','contract_obligations','contract_milestones',
    'contract_breach_alerts'
  ] loop
    execute format('drop policy if exists %I on public.%I', 'contract_manager_all', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (exists (select 1 from public.app_roles r where r.user_id=auth.uid() and r.active=true and r.role in (''owner'',''admin'',''manager''))) with check (exists (select 1 from public.app_roles r where r.user_id=auth.uid() and r.active=true and r.role in (''owner'',''admin'',''manager'')))',
      'contract_manager_all', t
    );
  end loop;
end $$;

create or replace view public.contract_control as
select
  c.id,
  c.deal_id,
  c.project_id,
  c.title,
  c.status,
  c.current_version,
  count(distinct v.id) as version_count,
  count(distinct a.id) as attachment_count,
  count(distinct ap.id) filter (where ap.status='pending') as pending_approvals,
  count(distinct s.id) filter (where s.status='pending') as pending_signatures,
  count(distinct o.id) filter (where o.status in ('open','overdue')) as open_obligations,
  count(distinct m.id) filter (where m.status in ('pending','overdue')) as open_milestones,
  count(distinct b.id) filter (where b.status in ('open','acknowledged')) as open_breaches
from public.contracts c
left join public.contract_versions v on v.contract_id=c.id
left join public.contract_attachments a on a.contract_id=c.id
left join public.contract_approvals ap on ap.contract_id=c.id
left join public.contract_signatures s on s.contract_id=c.id
left join public.contract_obligations o on o.contract_id=c.id
left join public.contract_milestones m on m.contract_id=c.id
left join public.contract_breach_alerts b on b.contract_id=c.id
group by c.id,c.deal_id,c.project_id,c.title,c.status,c.current_version;
