alter table public.construction_projects add column if not exists forecast_cost numeric not null default 0, add column if not exists revised_budget numeric not null default 0;

create table if not exists public.project_ledger (
 id bigint generated by default as identity primary key, project_id bigint not null references public.construction_projects(id) on delete cascade, entry_date date not null default current_date, entry_type text not null, description text, wbs_id bigint references public.project_wbs(id) on delete set null, phase_id bigint references public.project_phases(id) on delete set null, floor_id bigint references public.project_floors(id) on delete set null, unit_id bigint references public.project_units(id) on delete set null, contractor_name text, supplier_name text, material_key text, purchase_id bigint references public.project_procurement(id) on delete set null, invoice_ref text, payment_id bigint references public.project_payments(id) on delete set null, debit numeric not null default 0, credit numeric not null default 0, currency text not null default 'IRR', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), check (debit >= 0 and credit >= 0)
);
create table if not exists public.project_budgets (
 id bigint generated by default as identity primary key, project_id bigint not null references public.construction_projects(id) on delete cascade, version_no integer not null default 1, name text not null, status text not null default 'draft', total_budget numeric not null default 0, notes text, created_at timestamptz not null default now(), unique(project_id,version_no)
);
create table if not exists public.project_budget_lines (
 id bigint generated by default as identity primary key, budget_id bigint not null references public.project_budgets(id) on delete cascade, wbs_id bigint references public.project_wbs(id) on delete set null, phase_id bigint references public.project_phases(id) on delete set null, floor_id bigint references public.project_floors(id) on delete set null, unit_id bigint references public.project_units(id) on delete set null, contractor_name text, supplier_name text, material_key text, planned_amount numeric not null default 0, revised_amount numeric not null default 0, actual_amount numeric not null default 0, committed_amount numeric not null default 0, forecast_amount numeric not null default 0, notes text
);
create index if not exists idx_project_ledger_project_date on public.project_ledger(project_id,entry_date);
create index if not exists idx_project_ledger_wbs on public.project_ledger(project_id,wbs_id);
create index if not exists idx_project_budget_project on public.project_budgets(project_id,version_no desc);
create index if not exists idx_project_budget_lines_budget on public.project_budget_lines(budget_id);
alter table public.project_ledger enable row level security; alter table public.project_budgets enable row level security; alter table public.project_budget_lines enable row level security;
drop policy if exists buildwise_auth_all on public.project_ledger; create policy buildwise_auth_all on public.project_ledger for all to authenticated using (true) with check (true);
drop policy if exists buildwise_auth_all on public.project_budgets; create policy buildwise_auth_all on public.project_budgets for all to authenticated using (true) with check (true);
drop policy if exists buildwise_auth_all on public.project_budget_lines; create policy buildwise_auth_all on public.project_budget_lines for all to authenticated using (true) with check (true);
create or replace view public.project_accounting_summary with (security_invoker=true) as
select p.id project_id, coalesce(p.current_budget,0) budget, coalesce(p.revised_budget,0) revised_budget, coalesce(p.actual_cost,0) actual_cost,
coalesce((select sum(c.committed_amount) from public.project_commitments c where c.project_id=p.id),0) committed_cost,
coalesce(p.forecast_cost,0) forecast_cost,
greatest(coalesce(p.forecast_cost,0)-coalesce(p.actual_cost,0),0) remaining_cost,
greatest(coalesce(p.actual_cost,0),coalesce(p.forecast_cost,0),coalesce(p.current_budget,0),coalesce(p.revised_budget,0)) total_project_cost
from public.construction_projects p;