create table if not exists public.customer_shares (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  person_id bigint references public.crm_people(id) on delete set null,
  lead_id bigint references public.leads(id) on delete set null,
  property_id bigint references public.properties(id) on delete set null,
  deal_id bigint references public.deals(id) on delete set null,
  advisor_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'پیشنهاد BuildWise',
  message text not null default '',
  status text not null default 'sent' check (status in ('sent','viewed','responded','expired','revoked')),
  expires_at timestamptz not null default (now() + interval '72 hours'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customer_shares_advisor_idx on public.customer_shares(advisor_id, created_at desc);
create index if not exists customer_shares_property_idx on public.customer_shares(property_id);

create table if not exists public.customer_responses (
  id bigint generated by default as identity primary key,
  share_id bigint not null references public.customer_shares(id) on delete cascade,
  response_status text not null check (response_status in ('approved','rejected','interested','question')),
  message text not null default '',
  ai_summary text,
  ai_confidence numeric,
  created_at timestamptz not null default now()
);

create index if not exists customer_responses_share_idx on public.customer_responses(share_id, created_at desc);

alter table public.customer_shares enable row level security;
alter table public.customer_responses enable row level security;

drop policy if exists customer_shares_advisor_select on public.customer_shares;
create policy customer_shares_advisor_select on public.customer_shares
for select to authenticated
using (advisor_id = auth.uid() or exists (
  select 1 from public.app_roles r where r.user_id = auth.uid() and r.active = true and r.role in ('owner','admin','manager')
));

drop policy if exists customer_responses_advisor_select on public.customer_responses;
create policy customer_responses_advisor_select on public.customer_responses
for select to authenticated
using (exists (
  select 1 from public.customer_shares s
  where s.id = customer_responses.share_id
  and (s.advisor_id = auth.uid() or exists (
    select 1 from public.app_roles r where r.user_id = auth.uid() and r.active = true and r.role in ('owner','admin','manager')
  ))
));
